import {cropPotential} from './producer-seasons.js'
const escape=value=>String(value??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const number=value=>value===null||value===undefined||!Number.isFinite(value)?'—':value.toLocaleString('pt-BR',{maximumFractionDigits:2})
export function seasonReportHtml(client,season,history=[]){
 const headings=['Cultura','Área (ha)','Proj. (sc/ha)','Produção estimada (sc)','Reserva (sc)','Outros compradores (sc)','Potencial disponível (sc)','Meta (%)','Meta (sc)','Entrega declarada (sc)','Falta p/ meta (sc)']
 const rows=season.crops.map(row=>{const p=cropPotential(row);return `<tr>${[row.crop,number(row.areaHa),number(row.expectedYield),number(p.productionSc),number(row.retainedSc),number(row.otherBuyersSc),number(p.availableSc),number(row.targetSharePct),number(p.targetSc),number(row.deliveredSc),number(p.remainingSc)].map(v=>`<td>${escape(v)}</td>`).join('')}</tr>`}).join('')
 return `<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>VAL — Safra ${escape(season.season)}</title><style>@page{size:A4 landscape;margin:14mm}body{font:12px Arial;color:#183d32;padding:20px}h1{font-size:23px}h2{font-size:17px}table{border-collapse:collapse;width:100%;margin:20px 0}th,td{padding:8px;border:1px solid #d5e4dc;text-align:left}th{background:#edf6f1}tr{break-inside:avoid}.notice{padding:12px;background:#fff7dd}small{color:#526b60}@media print{body{padding:0}}</style><h1>VAL • Plano de safra e metas</h1><h2>${escape(client.name)} · ${escape(season.season)}</h2>${season.isDemo?'<p class="notice">DEMONSTRATIVO — sem validade para produtores reais.</p>':''}<p>Referência: ${escape(season.observedOn)} · Origem informada: ${escape(season.sourceNote)}</p><table><thead><tr>${headings.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table><p>Volumes em sacas de 60 kg. Produção estimada = área × produtividade projetada. Potencial disponível = produção estimada − reserva/consumo − volume destinado a outros compradores. Meta = potencial disponível × participação desejada.</p><p>Campos ausentes impedem o cálculo. Informe zero somente quando confirmado. Valores incompatíveis não geram saldo. Entregas são declarações do cadastro, sem conciliação com notas ou contratos. As culturas não são somadas em um único total de sacas.</p><h2>Histórico declarado de produtividade</h2><table><thead><tr><th>Safra</th><th>Cultura</th><th>Área (ha)</th><th>Produtividade realizada (sc/ha)</th><th>Origem / referência</th></tr></thead><tbody>${history.flatMap(s=>s.crops.filter(r=>r.actualYield!=null).map(r=>`<tr><td>${escape(s.season)}</td><td>${escape(r.crop)}</td><td>${number(r.areaHa)}</td><td>${number(r.actualYield)}</td><td>${escape(s.sourceNote)} · ${escape(s.observedOn)}</td></tr>`)).join('')||'<tr><td colspan="5">Sem histórico declarado.</td></tr>'}</tbody></table><small>Gerado em ${escape(new Date().toLocaleString('pt-BR'))}. Projeções e metas não constituem entrega confirmada, oportunidade ou fato inferido pela VAL.</small></html>`
}
export function openSeasonReport(client,season,history){
 const popup=window.open('','_blank')
 if(!popup)throw new Error('Permita a abertura do relatório no navegador.')
 popup.opener=null;popup.document.write(seasonReportHtml(client,season,history));popup.document.close();popup.focus();setTimeout(()=>popup.print(),200)
}
