import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'

test('migração legacy é versionada, bloqueada e preserva contexto técnico',async()=>{
  const sql=await readFile(new URL('../database/schema.sql',import.meta.url),'utf8')
  assert.match(sql,/pg_advisory_xact_lock/)
  assert.match(sql,/schema_migrations/)
  assert.match(sql,/legacy-v03-copy-v1/)
  assert.match(sql,/legacy-v03-technical-context-v2/)
  assert.match(sql,/legacy-v03-technical-context-canonical-v3/)
  assert.match(sql,/technical_context_legacy_v03/)
  assert.match(sql,/clients já canônico, mas technical_context ainda com o nome legado/)
  assert.match(sql,/'consultant_technical_context'/)
  assert.match(sql,/LEFT\(preferred_channel,60\)/)
  assert.match(sql,/RAISE WARNING 'VALOR 360 ignorou % perfil\(is\) legacy sem client_id canônico/)
  assert.match(sql,/WHERE legacy\.client_id IS NULL OR client\.id IS NULL/)
  assert.match(sql,/jsonb_build_object\('property',(?:legacy\.)?property_name,'crops','','area','','weeds'/)
  assert.match(sql,/'soil',(?:legacy\.)?soil_summary,'goal',(?:legacy\.)?producer_goal/)
  assert.match(sql,/SET valid_from=COALESCE\(legacy\.updated_at,memory\.valid_from\)/)
  assert.match(sql,/row_number\(\) OVER/)
  assert.match(sql,/INSERT INTO val_memories/)
  assert.match(sql,/profile_snapshot JSONB NOT NULL DEFAULT '\{\}'::jsonb/)
  assert.match(sql,/area_band VARCHAR\(120\)/)
  assert.match(sql,/source_key VARCHAR\(240\)/)
  assert.match(sql,/idx_profiles_tenant_source_key/)
  assert.match(sql,/idx_clients_owner_external_key/)
  assert.match(sql,/owner_user_id UUID REFERENCES users\(id\)/)
  assert.match(sql,/idx_integration_events_owner_external/)
  assert.match(sql,/separate-manual-technical-portfolio-v1/)
  assert.match(sql,/WHERE source='manual-do-agronomo'/)
  assert.match(sql,/password_hash TEXT/)
  assert.match(sql,/session_version INTEGER/)
  assert.match(sql,/SET profile_snapshot=survey\.result/)
  assert.match(sql,/CREATE TABLE IF NOT EXISTS app_workspace_data/)
  assert.match(sql,/workspace_id UUID PRIMARY KEY/)
  assert.match(sql,/professional_profile JSONB/)
  assert.match(sql,/CREATE TABLE IF NOT EXISTS app_records/)
  assert.match(sql,/CREATE TABLE IF NOT EXISTS usage_events/)
  assert.match(sql,/idx_usage_events_user_date/)
  assert.match(sql,/CREATE TABLE IF NOT EXISTS sog_producer_profiles/)
  assert.match(sql,/CREATE TABLE IF NOT EXISTS sog_negotiation_intents/)
  assert.match(sql,/CREATE TABLE IF NOT EXISTS sog_market_snapshots/)
  assert.match(sql,/UNIQUE \(tenant_id,owner_user_id,client_id\)/)
  assert.match(sql,/idx_sog_intents_owner_status/)
  assert.match(sql,/source_name VARCHAR\(240\) NOT NULL/)
  assert.match(sql,/COMMIT;/)
})

test('expansão de attachment UNLINKED é compatível e não destrutiva',async()=>{
  const sql=await readFile(new URL('../database/migrations/20260827_007_attachment_scan_provenance_expand.sql',import.meta.url),'utf8')
  assert.match(sql,/ALTER COLUMN client_id DROP NOT NULL/)
  assert.match(sql,/CREATE INDEX IF NOT EXISTS idx_val_attachments_unlinked_date/)
  assert.match(sql,/WHERE client_id IS NULL/)
  assert.doesNotMatch(sql,/\b(?:DELETE|TRUNCATE|DROP TABLE|DROP COLUMN|UPDATE)\b/i)
})
