import test from 'node:test'
import assert from 'node:assert/strict'
import {existsSync,readFileSync,statSync} from 'node:fs'
import {dirname,join} from 'node:path'
import {fileURLToPath} from 'node:url'

const root=join(dirname(fileURLToPath(import.meta.url)),'..')
const read=relative=>readFileSync(join(root,relative),'utf8')

test('brand mark keeps its accent centered and reuses the real logo on mobile',()=>{
 const logo=read('src/components/Logo.jsx')
 const topbar=read('src/components/Topbar.jsx')
 assert.match(logo,/rotate\(18 51 32\)/)
 assert.match(logo,/useId/)
 assert.match(topbar,/<Logo compact\/>/)
 assert.doesNotMatch(topbar,/topbar-mobile-mark|>C</)
})

test('pipeline presents discrete stages without a probability-style progress bar',()=>{
 const opportunities=read('src/pages/Opportunities.jsx')
 const rendered=opportunities.slice(opportunities.indexOf('return <div className="page-stack pipeline-page"'))
 assert.match(rendered,/pipeline-stage-progress/)
 assert.match(rendered,/Etapa \{index\+1\} de 4/)
 assert.doesNotMatch(rendered,/pipeline-probability|probabilidade/i)
})

test('navigation resets long pages and the responsive shell retains scroll clearance',()=>{
 const app=read('src/App.jsx')
 const styles=read('src/styles.css')
 assert.match(app,/window\.scrollTo\(\{top:0,left:0,behavior:'auto'\}\)/)
 assert.match(app,/document\.querySelector\('\.topbar h1'\)\?\.focus/)
 assert.match(styles,/body\{height:auto;min-height:100%;overflow-x:clip;overflow-y:auto/)
 assert.match(styles,/padding:18px max\(16px,env\(safe-area-inset-right\)\) calc\(112px \+ env\(safe-area-inset-bottom\)\)/)
 assert.match(styles,/\.pipeline-journey\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\);max-width:100%;overflow:visible/)
})

test('assisted review keeps all relationship fields optional through the final screen',()=>{
 const surveyForm=read('src/components/SurveyForm.jsx')
 assert.match(surveyForm,/requiredQuestions=questions\.filter\(question=>question\.id<=26\)/)
 assert.match(surveyForm,/currentQuestions\.filter\(question=>question\.id<=26&&/)
 assert.match(surveyForm,/question\.id>=27\?' \(opcional\)'/)
})

test('batch import has a responsive visual hierarchy and keeps the VALOR 360 PWA brand',()=>{
 const styles=read('src/styles.css')
 const app=read('src/App.jsx')
 const html=read('index.html')
 const manifest=JSON.parse(read('public/manifest.webmanifest'))
 assert.match(styles,/\.import-record-list\{display:grid/)
 assert.match(styles,/\.import-batch-progress\{padding:/)
 assert.match(styles,/@media\(max-width:700px\)[\s\S]*\.import-record-list\{grid-template-columns:1fr/)
 assert.match(app,/value!==''&&value!==null&&value!==undefined/)
 assert.match(html,/apple-mobile-web-app-title" content="VALOR 360"/)
 assert.equal(manifest.short_name,'VALOR 360')
})

test('negative optional answers use discovery labels instead of false opportunities',()=>{
 const profile=read('src/lib/profile.js')
 const client360=read('src/pages/Client360.jsx')
 const dashboard=read('src/pages/Dashboard.jsx')
 const opportunities=read('src/pages/Opportunities.jsx')
 assert.match(profile,/noAdditionalNeedPatterns/)
 assert.match(client360,/Nenhuma necessidade adicional declarada/)
 assert.match(client360,/Ainda não identificada/)
 assert.match(dashboard,/reconcilePipeline\(clients,/)
 assert.match(opportunities,/reconcilePipeline\(clients,/)
 assert.doesNotMatch(dashboard,/fallbackOpportunities|pipelineStages\[Math\.min\(index,2\)\]/)
 assert.doesNotMatch(opportunities,/clients\.map\(\(client,index\).*stage:/s)
})

test('producer dossier, access release and strategic action are exposed in the interface',()=>{
 const client360=read('src/pages/Client360.jsx')
 const dataHub=read('src/pages/DataHub.jsx')
 const settings=read('src/pages/Settings.jsx')
 const admin=read('src/pages/Admin.jsx')
 const app=read('src/App.jsx')
 const editor=read('src/components/ProducerProfileEditor.jsx')
 const access=read('src/components/AccessManagement.jsx')
 const val=read('src/components/ValPanel.jsx')
 assert.match(client360,/ProducerBusinessOverview/)
 assert.match(editor,/Visão global de compras e potencial/)
 assert.match(dataHub,/onUpdate=\{updateClient\}|ProducerProfileEditor/)
 assert.match(dataHub,/Excluir/)
 assert.match(editor,/Time do coração/)
 assert.match(editor,/Potencial em aberto/)
 assert.doesNotMatch(settings,/AccessManagement/)
 assert.match(admin,/AccessManagement/)
 assert.match(admin,/currentUser\?\.role!==['"]admin['"]/)
 assert.match(app,/currentUser\?\.role===['"]admin['"]&&<Admin/)
 assert.match(access,/carteira zerada|zero produtores/)
 assert.match(access,/\/api\/portfolio-admin\/users/)
 assert.doesNotMatch(access,/fetch\(['"]\/api\/admin\/users/)
 assert.match(access,/accessUserName\(user\)/)
 assert.match(access,/String\(user\?\.name\|\|user\?\.displayName\|\|user\?\.email\|\|'Usuário'\)/)
 assert.doesNotMatch(access,/user\.name\.split/)
 assert.match(val,/chooseMode/)
 assert.match(val,/pensamento estratégico completo/)
 assert.match(val,/AbortSignal\.timeout\(120000\)/)
})

test('technical memory confirmation remains textual and cannot render a response object as a toast',()=>{
 const client360=read('src/pages/Client360.jsx')
 const app=read('src/App.jsx')
 assert.match(client360,/onSaved\?\.\(['"]Complemento técnico salvo na nuvem e incorporado à memória da VAL\./)
 assert.doesNotMatch(client360,/onSaved\?\.\(payload\.context\)/)
 assert.match(app,/typeof message===['"]string['"]\?message:String\(message\?\.message/)
})

test('commercial editor uses Brazilian currency and derives the open potential before saving',()=>{
 const editor=read('src/components/ProducerProfileEditor.jsx')
 const currency=read('src/components/CurrencyInput.jsx')
 assert.match(currency,/>R\$</)
 assert.match(currency,/replace\(\/\\D\/g,['"]['"]\)/)
 assert.match(editor,/Math\.max\(0,totalPotential-currentPurchases\)/)
 assert.match(editor,/commercial:\{\.\.\.form\.commercial,openPotential\}/)
 assert.match(editor,/Crédito disponível — automático/)
})

test('global overview, usage metrics and administration stay protected by login and role',()=>{
 const server=read('server.js')
 const overview=read('src/components/ProducerBusinessOverview.jsx')
 const admin=read('src/pages/Admin.jsx')
 const sidebar=read('src/components/Sidebar.jsx')
 const mobile=read('src/components/MobileNav.jsx')
 assert.match(server,/\/api\/usage\/events/)
 assert.match(server,/\/api\/admin\/metrics/)
 assert.match(server,/\/overview/)
 assert.match(overview,/PostgreSQL por login/)
 assert.match(overview,/Manual do Agrônomo • mesmo login/i)
 assert.match(admin,/Somente a administração/)
 assert.match(sidebar,/currentUser\?\.role===['"]admin['"]/)
 assert.match(mobile,/currentUser\?\.role===['"]admin['"]/)
})

test('commercial cache is scoped and technical drafts expire with the browser session',()=>{
 const app=read('src/App.jsx')
 const settings=read('src/pages/Settings.jsx')
 const client360=read('src/pages/Client360.jsx')
 const server=read('server.js')
 assert.match(app,/opportunityCacheKey\(effectiveScope\)/)
 assert.match(app,/clearSessionPortfolioCache\(currentUser\?\.storageScope\)/)
 assert.match(app,/invalidateSession=notice=>\{clearSessionPortfolioCache[\s\S]*setClientList\(\[\]\);setVisits\(\[\]\);setOpportunities\(\[\]\);setSelected\(null\)/)
 assert.match(app,/if\(session\?\.authenticated\)rememberStorageScope\(session\.user\);else clearSessionPortfolioCache\(\)/)
 assert.match(settings,/opportunityCacheKey\(currentUser\?\.storageScope\)/)
 assert.match(settings,/reconcilePipeline\(clients,\[\.\.\.cached,\.\.\.opportunities\]\)/)
 assert.match(settings,/Playbook aprovado ativo/)
 assert.match(client360,/sessionStorage\.setItem\(storageKey/)
 assert.doesNotMatch(client360,/localStorage/)
 assert.match(server,/storageScope:auth\.storageScope\(session\)/)
})

test('production bundle receives the protected portfolio only from the server',()=>{
 const app=read('src/App.jsx')
 const dashboard=read('src/pages/Dashboard.jsx')
 assert.equal(existsSync(join(root,'src/data/clients.json')),false)
 assert.doesNotMatch(app,/data\/clients\.json|initialVisits|localStorage\.setItem\('valor360-clients'/)
 assert.match(app,/const \[clientList,setClientList\]=useState\(\[\]\)/)
 assert.match(app,/const serverClients=Array\.isArray\(data\.clients\)\?data\.clients:\[\]/)
 assert.match(app,/<Dashboard[^>]+opportunities=\{opportunities\}/)
 assert.match(dashboard,/reconcilePipeline\(clients,\[\.\.\.cachedItems,\.\.\.opportunities\]\)/)
 assert.doesNotMatch(dashboard,/nextVisit\?\.time\|\|['"]14:00/)
 assert.match(dashboard,/const scheduled=scheduledAtOf\(visit\)/)
 assert.match(dashboard,/recentVisits\.length\?recentVisits\.map/)
})

test('long portfolio guides use progressive disclosure and visits reject incomplete commitments',()=>{
 const clients=read('src/pages/Clients.jsx')
 const dataHub=read('src/pages/DataHub.jsx')
 const visits=read('src/pages/Visits.jsx')
 assert.match(clients,/visibleList=list\.slice\(0,visibleCount\)/)
 assert.match(clients,/Mostrar mais produtores/)
 assert.match(dataHub,/managedClientId/)
 assert.match(dataHub,/A carteira permanece recolhida/)
 assert.doesNotMatch(dataHub,/producer-manage-list">\{clients\.map/)
 assert.match(visits,/const formValid=Boolean/)
 assert.match(visits,/<select required/)
 assert.match(visits,/<input required min=\{today\(\)\} type="date"/)
 assert.match(visits,/disabled=\{saving\|\|!formValid\}/)
})

test('manual history and professional profile restore from the account cloud',()=>{
 const records=read('manual/app/records.ts')
 const recordsRoute=read('manual/app/api/records/route.ts')
 const workspace=read('manual/app/api/workspace/route.ts')
 const archive=read('manual/app/RecordsArchive.tsx')
 const manualPage=read('manual/app/page.tsx')
 assert.match(records,/listServerRecords/)
 assert.match(records,/fetch\(`\/api\/records\$\{query\}`/)
 assert.match(records,/method: "DELETE"/)
 assert.match(recordsRoute,/export async function DELETE/)
 assert.match(recordsRoute,/DELETE FROM app_records WHERE id = \$1 AND workspace_id = \$2/)
 assert.match(workspace,/professional_profile AS "professionalProfile"/)
 assert.match(manualPage,/professionalProfile: profile/)
 assert.match(archive,/ARQUIVO DA CONTA/)
 assert.doesNotMatch(archive,/Eles não ocupam o servidor|Excluir deste dispositivo/)
})

test('versioned atmospheric artwork is present and referenced by the visual system',()=>{
 const asset=join(root,'public/valor360-background-v1.webp')
 const header=readFileSync(asset).subarray(0,12)
 assert.ok(statSync(asset).size>10_000)
 assert.equal(header.subarray(0,4).toString(),'RIFF')
 assert.equal(header.subarray(8,12).toString(),'WEBP')
 const styles=read('src/styles.css')
 assert.match(styles,/url\('\/valor360-background-v1\.webp'\)/)
 assert.match(styles,/background-position:center,center,61% center/)
 assert.match(styles,/background-position:center,center,70% center/)
})

test('inteligência agronômica executa o Manual dentro da sessão do VALOR 360',()=>{
 const agro=read('src/pages/Agro.jsx')
 const app=read('src/App.jsx')
 const manualConfig=read('manual/next.config.ts')
 const manualPage=read('manual/app/page.tsx')
 const manualStyles=read('manual/app/globals.css')
assert.match(agro,/src="\/tecnico\?embedded=1"/)
 assert.match(agro,/Mesmo login ativo/)
 assert.match(app,/<Agro clients=\{clientList\}\/>/)
 assert.match(manualConfig,/basePath: "\/tecnico"/)
 assert.match(manualPage,/fetch\("\/api\/technical\/bootstrap"/)
 assert.match(manualStyles,/\.valor360-embedded body \{[\s\S]*var\(--bg\)/)
 assert.match(manualStyles,/\.valor360-embedded \.app-shell \{[\s\S]*background: var\(--bg\)/)
 assert.match(manualStyles,/\.valor360-embedded input,[\s\S]*caret-color: var\(--lime\)/)
})
