[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "node server/migrate.js"
startCommand = "node server/start.js"
healthcheckPath = "/live"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
