import ProducerSeasons,{useProducerSeasons} from '../components/ProducerSeasons'
import {cropPotential} from '../lib/producer-seasons'
import React,{lazy,Suspense,useEffect,useState} from 'react'
import {ArrowRight,CalendarDays,ChartNoAxesCombined,ChevronDown,FileText,History,LandPlot,Lightbulb,Map,MapPin,MessageSquareText,Sprout,Target,Users,WalletCards,Wheat} from 'lucide-react'
import {ProducerDocuments,ProducerGrains} from '../components/ProducerResources'
import SatelliteMap from '../components/map/SatelliteMap'
import {commercialMetrics} from '../lib/commercial-metrics'
import {selectLatestEvidenceVisit} from '../lib/copilot-view-model'
import {cropColor,displayDatum,formatNumber,hasValue,isDemoRecord,scopedRecords,seasonDisplay,nextPlanAction} from '../lib/producer-display'
import '../val-producer360-premium.css'
const Details=lazy(()=>import('./Client360Details'))
const tabs=[['overview','Visão geral',Users],['map','Mapa e talhões',Map],['season','Safra',Sprout],['agronomy','Agronomia',Sprout],['commercial','Comercial',Target],['grains','Grãos',Wheat],['credit','Crédito',WalletCards],['history','Histórico',History],['documents','Documentos',FileText]]
const date=value=>{if(!value)return 'Não informado';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'Não informado':parsed.toLocaleDateString('pt-BR',{day:'numeric',month:'short',year:'numeric'})}
const guidance={Analítico:['Leve dados e comparativos.','Conecte manejo, produtividade e margem.','Construa alternativas e cenários.'],Relacional:['Retome o histórico e os compromissos.','Valorize confiança e acompanhamento.'],Inovador:['Apresente evidências de campo.','Combine um teste e critérios de avaliação.'],Conservador:['Apresente resultados comprovados.','Esclareça os riscos e próximos passos.']}
const Skeleton=()=> <span className="p360-skeleton" role="status" aria-label="Carregando dado"/>
const Empty=({children,action,onAction})=><div className="p360-empty"><LandPlot size={28}/><p>{children}</p>{action&&<button onClick={onAction}>{action}<ArrowRight size={14}/></button>}</div>
function Metric({icon:Icon,label,value,detail='Não informado',loading=false,demo=false,kind='REAL DATA'}){
 const datum=displayDatum(value,{kind,demo})
 return <article className="p360-metric" data-provenance={datum.kind}><span className="p360-icon"><Icon size={19}/></span><div><small>{label}</small>{loading?<Skeleton/>:<strong>{hasValue(datum.value)?datum.value:'—'}</strong>}<span>{detail}</span></div></article>
}
function Timeline({events}){return events.length?<ol className="p360-timeline">{events.slice(0,5).map((event,index)=><li key={event.id||index}><span className="p360-icon"><CalendarDays size={16}/></span><time>{date(event.at)}</time><div><b>{event.title}</b><p>{event.summary||'Sem observação registrada'}</p></div></li>)}</ol>:<Empty>Nenhum acontecimento registrado</Empty>}
export default function Client360(props){
 const {client,visits=[],opportunities=[],currentUser,onBack,onPrepare,onAsk,onNewOpportunity,onRefreshPortfolio}=props
 const [tab,setTab]=useState(props.activeTab||'overview')
 useEffect(()=>{if(props.activeTab)setTab(props.activeTab)},[props.activeTab])
 const [selectedSeason,setSelectedSeason]=useState('')
 const [resource,setResource]=useState({status:'loading',data:null,error:''})
 const [revision,setRevision]=useState(0)
 const budget=useProducerSeasons(client.id)
 const demo=isDemoRecord(client)||resource.data?.isDemo===true||budget.isDemo===true
 const metrics=commercialMetrics(client)
 useEffect(()=>{
  const controller=new AbortController();setResource({status:'loading',data:null,error:''});const timeout=setTimeout(()=>controller.abort('timeout'),15000)
  fetch(`/api/clients/${encodeURIComponent(client.id)}/workspace`,{signal:controller.signal}).then(async response=>{if(response.status===401)window.dispatchEvent(new Event('valor360:unauthorized'));if(!response.ok)throw new Error('Não foi possível carregar as propriedades.');return response.json()}).then(data=>{if(!controller.signal.aborted)setResource({status:'ready',data,error:''})}).catch(error=>{if(!controller.signal.aborted||controller.signal.reason==='timeout')setResource({status:'error',data:null,error:controller.signal.reason==='timeout'?'A consulta demorou demais. Tente novamente.':error.message})}).finally(()=>clearTimeout(timeout))
  return()=>{clearTimeout(timeout);controller.abort()}
 },[client.id,revision])
 const profile=resource.data
 const seasons=profile?.seasons||[]
 const seasonNames=[...new Set([...seasons.map(row=>row.season),...budget.seasons.map(row=>row.season)].filter(Boolean))].sort().reverse()
 const season=seasonNames.includes(selectedSeason)?selectedSeason:seasonNames[0]||''
 const declaredSeason=budget.seasons.find(row=>row.season===season)
 const seasonRows=declaredSeason?declaredSeason.crops.map(row=>({crop:row.crop,areaHa:row.areaHa,productivityTarget:row.expectedYield,estimatedProductionSc:cropPotential(row).productionSc,reason:'Cadastro consolidado do produtor'})):seasonDisplay(seasons,{season,complete:profile?.complete!==false,demo})
 const nextAction=nextPlanAction(profile?.plan)
 const fields=(profile?.fields||[]).filter(field=>demo||!isDemoRecord(field))
 const ownVisits=scopedRecords(visits,client)
 const ownOpportunities=scopedRecords(opportunities,client)
 const active=ownOpportunities.filter(item=>!/fechado|ganho|perdido|cancelado|closed|won|lost/i.test(String(item.stage||'')))
 const lastVisit=selectLatestEvidenceVisit(ownVisits,client.id)
 const events=[...ownVisits.map(item=>({id:`visit-${item.id}`,title:item.status?`Visita • ${item.status}`:'Visita registrada',summary:item.summary||item.objective,at:item.completedAt||item.occurredAt||item.date||item.scheduledAt})),...ownOpportunities.map(item=>({id:`opp-${item.id}`,title:item.title||'Oportunidade registrada',summary:item.stage,at:item.updatedAt||item.createdAt}))].filter(item=>item.at&&!Number.isNaN(new Date(item.at).getTime())).sort((a,b)=>new Date(b.at)-new Date(a.at))
 const profileKnown=metrics.profileMeasured&&hasValue(client.primaryProfile)
 const cropNames=Array.isArray(client.cultures)?client.cultures.join(', '):client.cultures
 const location=profile?.property?.location||client.location
 const polygons=fields.filter(field=>field.points?.length>=3).map(field=>({points:field.points,label:[field.name,seasons.find(row=>row.fieldId===field.id&&row.season===season)?.crop||field.crop].filter(Boolean).join(' • '),color:cropColor(seasons.find(row=>row.fieldId===field.id&&row.season===season)?.crop||field.crop)}))
 const knownCredit=hasValue(client.commercial?.creditLimit)
 const refresh=async()=>{setRevision(value=>value+1);await onRefreshPortfolio?.()}
 const go=next=>{setTab(next);props.onTabChange?.(next)}
 const metricProps={demo}
 const seasonCard=<section className="p360-card"><header><h3>Indicadores da safra</h3><label className="p360-season-select">Safra<select aria-label="Selecionar safra" value={season} onChange={event=>setSelectedSeason(event.target.value)} disabled={!seasonNames.length}>{seasonNames.length?seasonNames.map(name=><option key={name}>{name}</option>):<option value="">Não informada</option>}</select></label></header><div className="p360-kpis p360-season">{(seasonRows.length?seasonRows:[{crop:'Soja'},{crop:'Milho'},{crop:'Trigo'}]).map(row=><Metric key={row.crop} {...metricProps} icon={Sprout} label={row.crop} loading={resource.status==='loading'||budget.status==='loading'} value={hasValue(row.areaHa)?`${formatNumber(row.areaHa)} ha`:null} detail={hasValue(row.productivityTarget)?`Meta: ${formatNumber(row.productivityTarget)} sc/ha`:row.reason||'Área da safra não informada'} kind="DERIVED DATA"/>)}<Metric {...metricProps} icon={Wheat} label="Produção estimada" loading={resource.status==='loading'||budget.status==='loading'} value={seasonRows.length===1&&hasValue(seasonRows[0].estimatedProductionSc)?`${formatNumber(seasonRows[0].estimatedProductionSc)} sc`:null} detail={seasonRows.length>1?'Ver estimativa por cultura':'Produção ainda não estimada'} kind="ESTIMATE"/><Metric {...metricProps} icon={ChartNoAxesCombined} label="Comercializado" detail="Sem movimentações conciliadas"/><Metric {...metricProps} icon={Wheat} label="Saldo estimado" detail="Ainda não calculado"/></div>{seasonRows.length>1&&<div className="p360-crop-estimates">{seasonRows.map(row=><span key={row.crop} data-provenance={demo?'DEMO':hasValue(row.estimatedProductionSc)?'ESTIMATE':'MISSING'}><b>{row.crop}</b> • {hasValue(row.estimatedProductionSc)?`${formatNumber(row.estimatedProductionSc)} sc estimadas`:'Produção ainda não estimada'}</span>)}</div>}{resource.status==='error'&&<p role="alert">{resource.error}</p>}{budget.status==='error'&&<p role="alert">{budget.error}</p>}</section>
 return <div className="p360-page">
  <nav className="p360-breadcrumb" aria-label="Localização"><button onClick={onBack}>Clientes</button><span>›</span><span>Produtor 360</span></nav>
  <header className="p360-header"><div className="p360-avatar" aria-hidden="true"><Sprout/></div><div className="p360-identity"><h2>{client.name}{client.status==='active'&&<span className="p360-badge">Ativo</span>}{demo&&<span className="p360-demo">Dados demonstrativos</span>}</h2><p><MapPin size={13}/>{client.municipality||'Município não informado'}<span>•</span>{client.area||'Área não informada'}<span>•</span>{cropNames||'Culturas não informadas'}</p><small>Responsável: {currentUser?.name||currentUser?.email||'Você'}</small></div><div className="p360-actions"><button onClick={onPrepare}><CalendarDays size={15}/>Registrar visita</button><button onClick={onNewOpportunity}><Target size={15}/>Nova oportunidade</button><details><summary>Mais ações<ChevronDown size={14}/></summary><div><button onClick={()=>go('profile')}>Editar cadastro e perfil</button><button onClick={onPrepare}>Preparar visita</button><button onClick={onAsk}>Perguntar à VAL</button></div></details></div></header>
  {demo&&<p className="p360-demo-notice" role="status">Ambiente demonstrativo deste produtor. Informações simuladas, sem validade técnica ou comercial.</p>}
  <div className="p360-tabs" role="tablist" aria-label="Seções do produtor">{tabs.map(([id,label,Icon])=><button role="tab" id={`p360-tab-${id}`} aria-controls="p360-panel" aria-selected={tab===id} tabIndex={tab===id?0:-1} key={id} onClick={()=>go(id)} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const index=tabs.findIndex(item=>item[0]===id);const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;go(tabs[next][0]);document.getElementById(`p360-tab-${tabs[next][0]}`)?.focus()}}}><Icon size={15}/>{label}</button>)}</div>
  <div id="p360-panel" role="tabpanel" aria-labelledby={`p360-tab-${tab==='profile'?'overview':tab}`}>
  {tab==='overview'&&<>
   <section className="p360-kpis" aria-label="Indicadores do produtor"><Metric {...metricProps} icon={Users} label="Área total" value={client.area} detail="Área cadastrada"/><Metric {...metricProps} icon={Sprout} label="Culturas principais" value={cropNames} detail={cropNames?'Culturas cadastradas':'Não informado'}/><Metric {...metricProps} icon={CalendarDays} label="Última visita" value={lastVisit?date(lastVisit.completedAt||lastVisit.occurredAt||lastVisit.date||lastVisit.scheduledAt):null} detail={lastVisit?'Visita comprovada':'Nenhuma visita comprovada'}/><Metric {...metricProps} icon={Target} label="Oportunidades" value={`${active.length} ativas`} detail={active.length?'Na carteira deste produtor':'Nenhuma oportunidade ativa'} kind="DERIVED DATA"/><Metric {...metricProps} icon={Wheat} label="Saldo estimado de grãos" detail="Ainda não calculado"/><Metric {...metricProps} icon={WalletCards} label="Sinal de crédito" detail="Sem informação de crédito"/></section>
   <section className="p360-card"><header><h3>Resumo do produtor</h3><button onClick={()=>go('profile')}>Ver perfil completo<ArrowRight size={14}/></button></header><div className="p360-summary"><div className="p360-profile" data-provenance={demo?'DEMO':profileKnown?'REAL DATA':'MISSING'}><ChartNoAxesCombined className="p360-profile-icon"/><div><small>Perfil comportamental</small><h3>{profileKnown?client.primaryProfile:'Não informado'}</h3><p>{profileKnown?'Perfil registrado. Consulte a origem e as evidências antes de orientar a abordagem.':'Ainda não há perfil comportamental registrado.'}</p></div><div className="p360-guidance"><small>Como abordar</small>{profileKnown&&guidance[client.primaryProfile]?<ul>{guidance[client.primaryProfile].map(text=><li key={text}>{text}</li>)}</ul>:<p>Registre preferências e evidências para orientar a abordagem.</p>}</div></div><div className="p360-next" data-provenance={nextAction?(demo?'DEMO':'ESTIMATE'):'MISSING'}><Lightbulb size={23}/><div><b>Próxima melhor ação</b><p>{resource.status==='loading'?<Skeleton/>:nextAction?nextAction.description||nextAction.title:'Ainda não definida com evidências suficientes.'}</p>{nextAction&&<small className="p360-source-note">{nextAction.planStatus==='PROPOSED'?'Sugestão do plano • requer validação':'Plano de visita registrado'}</small>}<button onClick={onPrepare}>Ver plano de visita</button></div></div></div></section>
   <div className="p360-two"><section className="p360-card"><header><h3>Propriedades e talhões</h3><button onClick={()=>go('map')}>Abrir mapa<ArrowRight size={14}/></button></header>{resource.status==='error'?<Empty action="Tentar novamente" onAction={()=>setRevision(value=>value+1)}>{resource.error}</Empty>:<div className="p360-map-row"><div>{resource.status==='loading'?<div className="p360-map-loading"><Skeleton/></div>:location||polygons.length?<SatelliteMap center={location} pins={location?[{...location,title:profile?.property?.name||'Sede'}]:[]} polygons={polygons} height={230}/>:<Empty action="Adicionar localização" onAction={()=>go('map')}>Nenhuma localização cadastrada</Empty>}<div className="p360-legend">{['Soja','Milho','Trigo','Outras'].map(crop=><span key={crop}><i style={{background:cropColor(crop)}}/>{crop}</span>)}</div></div><div className="p360-map-stats"><Metric {...metricProps} icon={LandPlot} label="Propriedades" loading={resource.status==='loading'} value={resource.status==='ready'?profile?.properties?.length??0:null} detail="Cadastradas" kind="DERIVED DATA"/><Metric {...metricProps} icon={Map} label="Talhões" loading={resource.status==='loading'} value={resource.status==='ready'?fields.length:null} detail="Em todas as propriedades" kind="DERIVED DATA"/><Metric {...metricProps} icon={LandPlot} label="Área total" value={client.area} detail="Área cadastrada"/><Metric {...metricProps} icon={Sprout} label="Área produtiva" detail="Não consolidada"/></div></div>}</section><section className="p360-card"><header><h3>Últimos acontecimentos</h3><button onClick={()=>go('history')}>Ver todos<ArrowRight size={14}/></button></header><Timeline events={events}/></section></div>
   {seasonCard}<button onClick={()=>go('season')}>Cadastrar safras e gerar relatório de metas</button>
  </>}
  {tab==='season'&&<>{seasonCard}<ProducerSeasons key={client.id} client={client} resource={budget}/></>}
  {tab==='grains'&&<>{seasonCard}<ProducerGrains client={client} onAsk={onAsk}/></>}
  {tab==='credit'&&<section className="p360-card"><header><h3>Crédito</h3></header><Metric {...metricProps} icon={WalletCards} label="Limite cadastrado" value={knownCredit?Number(client.commercial.creditLimit).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):null} detail={knownCredit?'Registro comercial, não é análise de necessidade':'Sem informação de crédito'}/><Empty>Necessidade de crédito ainda não calculada.</Empty></section>}
  {tab==='documents'&&<ProducerDocuments client={client} onAsk={onAsk}/>}
  {['map','profile','commercial','agronomy','history'].includes(tab)&&<Suspense fallback={<Skeleton/>}>{tab==='history'&&<section className="p360-card"><header><h3>Histórico do produtor</h3></header><Timeline events={events}/></section>}<Details {...props} section={tab} onRefreshPortfolio={refresh}/></Suspense>}
  {tab==='map'&&<ProducerSeasons key={client.id} client={client} resource={budget}/>}
  </div>
 </div>
}
