import React,{lazy,Suspense,useEffect,useState} from 'react'
import {ArrowRight,CalendarDays,ChartNoAxesCombined,ChevronDown,FileText,History,LandPlot,Lightbulb,Map,MapPin,MessageSquareText,Sprout,Target,Users,WalletCards,Wheat} from 'lucide-react'
import SatelliteMap from '../components/map/SatelliteMap'
import {commercialMetrics} from '../lib/commercial-metrics'
import {selectLatestEvidenceVisit} from '../lib/copilot-view-model'
import {cropColor,displayDatum,formatNumber,hasValue,isDemoRecord,scopedRecords} from '../lib/producer-display'
import '../val-producer360-premium.css'
const Details=lazy(()=>import('./Client360Details'))
const tabs=[['overview','Visão geral',Users],['map','Mapa e talhões',Map],['season','Safra',Sprout],['agronomy','Agronomia',Sprout],['commercial','Comercial',Target],['grains','Grãos',Wheat],['credit','Crédito',WalletCards],['history','Histórico',History],['documents','Documentos',FileText]]
const date=value=>{if(!value)return 'Não informado';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'Não informado':parsed.toLocaleDateString('pt-BR',{day:'numeric',month:'short',year:'numeric'})}
const guidance={Analítico:['Leve dados e comparativos.','Conecte manejo, produtividade e margem.','Construa alternativas e cenários.'],Relacional:['Retome o histórico e os compromissos.','Valorize confiança e acompanhamento.'],Inovador:['Apresente evidências de campo.','Combine um teste e critérios de avaliação.'],Conservador:['Apresente resultados comprovados.','Esclareça os riscos e próximos passos.']}
const Skeleton=()=> <span className="p360-skeleton" role="status" aria-label="Carregando dado"/>
const Empty=({children,action,onAction})=><div className="p360-empty"><LandPlot size={28}/><p>{children}</p>{action&&<button onClick={onAction}>{action}<ArrowRight size={14}/></button>}</div>
function Metric({icon:Icon,label,value,detail='Não informado',loading=false,demo=false,kind='REAL DATA'}){
 const datum=displayDatum(value,{kind,demo})
 return <article className="p360-metric" data-provenance={datum.kind}><span className="p360-icon"><Icon size={19}/></span><div><small>{label}</small>{loading?<Skeleton/>:<strong>{hasValue(datum.value)?datum.value:'—'}</strong>}<span>{detail}</span></div></article>
}
function Timeline({events}){return events.length?<ol className="p360-timeline">{events.slice(0,5).map((event,index)=><li key={event.id||index}><span className="p360-icon"><CalendarDays size={16}/></span><time>{date(event.at)}</time><div><b>{event.title}</b><p>{event.summary||'Sem observação registrada'}</p></div></li>)}</ol>:<Empty>Nenhum acontecimento registrado</Empty>}
export default function Client360(props){
 const {client,visits=[],opportunities=[],currentUser,onBack,onPrepare,onAsk,onNewOpportunity,onRefreshPortfolio}=props
 const [tab,setTab]=useState('overview')
 const [resource,setResource]=useState({status:'loading',data:null,error:''})
 const [revision,setRevision]=useState(0)
 const demo=isDemoRecord(client)
 const metrics=commercialMetrics(client)
 useEffect(()=>{
  const controller=new AbortController();setResource({status:'loading',data:null,error:''})
  fetch(`/api/clients/${encodeURIComponent(client.id)}/property`,{signal:controller.signal}).then(async response=>{if(response.status===401)window.dispatchEvent(new Event('valor360:unauthorized'));if(!response.ok)throw new Error('Não foi possível carregar as propriedades.');return response.json()}).then(data=>{if(!controller.signal.aborted)setResource({status:'ready',data,error:''})}).catch(error=>{if(!controller.signal.aborted)setResource({status:'error',data:null,error:error.message})})
  return()=>controller.abort()
 },[client.id,revision])
 const profile=resource.data
 const fields=(profile?.fields||[]).filter(field=>demo||!isDemoRecord(field))
 const ownVisits=scopedRecords(visits,client)
 const ownOpportunities=scopedRecords(opportunities,client)
 const active=ownOpportunities.filter(item=>!/fechado|ganho|perdido|cancelado|closed|won|lost/i.test(String(item.stage||'')))
 const lastVisit=selectLatestEvidenceVisit(ownVisits,client.id)
 const events=[...ownVisits.map(item=>({id:`visit-${item.id}`,title:item.status?`Visita • ${item.status}`:'Visita registrada',summary:item.summary||item.objective,at:item.completedAt||item.occurredAt||item.date||item.scheduledAt})),...ownOpportunities.map(item=>({id:`opp-${item.id}`,title:item.title||'Oportunidade registrada',summary:item.stage,at:item.updatedAt||item.createdAt}))].filter(item=>item.at&&!Number.isNaN(new Date(item.at).getTime())).sort((a,b)=>new Date(b.at)-new Date(a.at))
 const profileKnown=metrics.profileMeasured&&hasValue(client.primaryProfile)
 const cropNames=Array.isArray(client.cultures)?client.cultures.join(', '):client.cultures
 const location=profile?.property?.location||client.location
 const polygons=fields.filter(field=>field.points?.length>=3).map(field=>({points:field.points,label:[field.name,field.crop].filter(Boolean).join(' • '),color:cropColor(field.crop)}))
 const knownCredit=hasValue(client.commercial?.creditLimit)
 const refresh=async()=>{setRevision(value=>value+1);await onRefreshPortfolio?.()}
 const go=next=>setTab(next)
 const metricProps={demo}
 const seasonCard=<section className="p360-card"><header><h3>Indicadores da safra</h3><span>{[...new Set(fields.map(field=>field.season).filter(Boolean))].join(' • ')||'Safra não informada'}</span></header><div className="p360-kpis p360-season">{['Soja','Milho','Trigo'].map(crop=><Metric key={crop} {...metricProps} icon={Sprout} label={crop} detail="Área da safra não consolidada"/>)}<Metric {...metricProps} icon={Wheat} label="Produção estimada" detail="Produção ainda não estimada"/><Metric {...metricProps} icon={ChartNoAxesCombined} label="Comercializado" detail="Sem dados consolidados"/><Metric {...metricProps} icon={Wheat} label="Saldo estimado" detail="Ainda não calculado"/></div></section>
 return <div className="p360-page">
  <nav className="p360-breadcrumb" aria-label="Localização"><button onClick={onBack}>Clientes</button><span>›</span><span>Produtor 360</span></nav>
  <header className="p360-header"><div className="p360-avatar" aria-hidden="true"><Sprout/></div><div className="p360-identity"><h2>{client.name}{client.status==='active'&&<span className="p360-badge">Ativo</span>}{demo&&<span className="p360-demo">Dados demonstrativos</span>}</h2><p><MapPin size={13}/>{client.municipality||'Município não informado'}<span>•</span>{client.area||'Área não informada'}<span>•</span>{cropNames||'Culturas não informadas'}</p><small>Responsável: {currentUser?.name||currentUser?.email||'Você'}</small></div><div className="p360-actions"><button onClick={onPrepare}><CalendarDays size={15}/>Registrar visita</button><button onClick={onNewOpportunity}><Target size={15}/>Nova oportunidade</button><details><summary>Mais ações<ChevronDown size={14}/></summary><div><button onClick={()=>go('profile')}>Editar cadastro e perfil</button><button onClick={onPrepare}>Preparar visita</button><button onClick={onAsk}>Perguntar à VAL</button></div></details></div></header>
  {demo&&<p className="p360-demo-notice" role="status">Ambiente demonstrativo deste produtor. Informações simuladas, sem validade técnica ou comercial.</p>}
  <div className="p360-tabs" role="tablist" aria-label="Seções do produtor">{tabs.map(([id,label,Icon])=><button role="tab" id={`p360-tab-${id}`} aria-controls="p360-panel" aria-selected={tab===id} tabIndex={tab===id?0:-1} key={id} onClick={()=>go(id)} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const index=tabs.findIndex(item=>item[0]===id);const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;go(tabs[next][0]);document.getElementById(`p360-tab-${tabs[next][0]}`)?.focus()}}}><Icon size={15}/>{label}</button>)}</div>
  <div id="p360-panel" role="tabpanel" aria-labelledby={`p360-tab-${tab==='profile'?'overview':tab}`}>
  {tab==='overview'&&<>
   <section className="p360-kpis" aria-label="Indicadores do produtor"><Metric {...metricProps} icon={Users} label="Área total" value={client.area} detail="Área cadastrada"/><Metric {...metricProps} icon={Sprout} label="Culturas principais" value={cropNames} detail={cropNames?'Culturas cadastradas':'Não informado'}/><Metric {...metricProps} icon={CalendarDays} label="Última visita" value={lastVisit?date(lastVisit.completedAt||lastVisit.occurredAt||lastVisit.date||lastVisit.scheduledAt):null} detail={lastVisit?'Visita comprovada':'Nenhuma visita comprovada'}/><Metric {...metricProps} icon={Target} label="Oportunidades" value={`${active.length} ativas`} detail={active.length?'Na carteira deste produtor':'Nenhuma oportunidade ativa'} kind="DERIVED DATA"/><Metric {...metricProps} icon={Wheat} label="Saldo estimado de grãos" detail="Ainda não calculado"/><Metric {...metricProps} icon={WalletCards} label="Sinal de crédito" detail="Sem informação de crédito"/></section>
   <section className="p360-card"><header><h3>Resumo do produtor</h3><button onClick={()=>go('profile')}>Ver perfil completo<ArrowRight size={14}/></button></header><div className="p360-summary"><div className="p360-profile" data-provenance={demo?'DEMO':profileKnown?'REAL DATA':'MISSING'}><ChartNoAxesCombined className="p360-profile-icon"/><div><small>Perfil comportamental</small><h3>{profileKnown?client.primaryProfile:'Não informado'}</h3><p>{profileKnown?'Perfil registrado. Consulte a origem e as evidências antes de orientar a abordagem.':'Ainda não há perfil comportamental registrado.'}</p></div><div className="p360-guidance"><small>Como abordar</small>{profileKnown&&guidance[client.primaryProfile]?<ul>{guidance[client.primaryProfile].map(text=><li key={text}>{text}</li>)}</ul>:<p>Registre preferências e evidências para orientar a abordagem.</p>}</div></div><div className="p360-next"><Lightbulb size={23}/><div><b>Próxima melhor ação</b><p>Ainda não definida com evidências suficientes.</p><button onClick={onPrepare}>Ver plano de visita</button></div></div></div></section>
   <div className="p360-two"><section className="p360-card"><header><h3>Propriedades e talhões</h3><button onClick={()=>go('map')}>Abrir mapa<ArrowRight size={14}/></button></header>{resource.status==='error'?<Empty action="Tentar novamente" onAction={()=>setRevision(value=>value+1)}>{resource.error}</Empty>:<div className="p360-map-row"><div>{resource.status==='loading'?<div className="p360-map-loading"><Skeleton/></div>:location||polygons.length?<SatelliteMap center={location} pins={location?[{...location,title:profile?.property?.name||'Sede'}]:[]} polygons={polygons} height={230}/>:<Empty action="Adicionar localização" onAction={()=>go('map')}>Nenhuma localização cadastrada</Empty>}<div className="p360-legend">{['Soja','Milho','Trigo','Outras'].map(crop=><span key={crop}><i style={{background:cropColor(crop)}}/>{crop}</span>)}</div></div><div className="p360-map-stats"><Metric {...metricProps} icon={LandPlot} label="Propriedades" loading={resource.status==='loading'} value={resource.status==='ready'?profile?.properties?.length??0:null} detail="Cadastradas" kind="DERIVED DATA"/><Metric {...metricProps} icon={Map} label="Talhões" loading={resource.status==='loading'} value={resource.status==='ready'?fields.length:null} detail="Na propriedade exibida" kind="DERIVED DATA"/><Metric {...metricProps} icon={LandPlot} label="Área da propriedade" value={hasValue(profile?.property?.areaHa)?`${formatNumber(profile.property.areaHa)} ha`:null} detail={profile?.property?.name||'Não informado'}/><Metric {...metricProps} icon={Sprout} label="Área produtiva" detail="Não consolidada"/></div></div>}</section><section className="p360-card"><header><h3>Últimos acontecimentos</h3><button onClick={()=>go('history')}>Ver todos<ArrowRight size={14}/></button></header><Timeline events={events}/></section></div>
   {seasonCard}
  </>}
  {tab==='season'&&seasonCard}
  {tab==='grains'&&<section className="p360-card"><header><h3>Grãos</h3></header>{seasonCard}<Empty action="Consultar registros com a VAL" onAction={()=>onAsk?.({prompt:'Quais registros de grãos existem para este produtor?'})}>Nenhuma posição de grãos consolidada nesta visão.</Empty></section>}
  {tab==='credit'&&<section className="p360-card"><header><h3>Crédito</h3></header><Metric {...metricProps} icon={WalletCards} label="Limite cadastrado" value={knownCredit?Number(client.commercial.creditLimit).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):null} detail={knownCredit?'Registro comercial, não é análise de necessidade':'Sem informação de crédito'}/><Empty>Necessidade de crédito ainda não calculada.</Empty></section>}
  {tab==='documents'&&<section className="p360-card"><header><h3>Documentos</h3></header><Empty action="Anexar documento à VAL" onAction={()=>onAsk?.({capture:'file'})}>Consulte e envie documentos pelo Copiloto deste produtor.</Empty></section>}
  {['map','profile','commercial','agronomy','history'].includes(tab)&&<Suspense fallback={<Skeleton/>}>{tab==='history'&&<section className="p360-card"><header><h3>Histórico do produtor</h3></header><Timeline events={events}/></section>}<Details {...props} section={tab} onRefreshPortfolio={refresh}/></Suspense>}
  </div>
 </div>
}
