import React,{useEffect,useMemo,useState} from 'react'
import {ArrowRight,BarChart3,Check,ClipboardCheck,Copy,Inbox,Link2,MessageCircle,Plus,Sparkles,UserRoundCheck,UsersRound} from 'lucide-react'
import SurveyForm from '../components/SurveyForm'
import QuestionnaireImport from '../components/QuestionnaireImport'

const statusLabel=status=>status==='respondido'?'Respondido':status==='integrado'?'Integrado ao 360':'Aguardando'

export default function Questionnaire({onCreate,onOpen,onNotify}){
 const [mode,setMode]=useState('central')
 const [surveys,setSurveys]=useState([])
 const [producerName,setProducerName]=useState('')
 const [loading,setLoading]=useState(false)
 const [error,setError]=useState('')
 const [created,setCreated]=useState(null)
 const [assistedResult,setAssistedResult]=useState(null)
 const [importedAnswers,setImportedAnswers]=useState({})
 const [importQueue,setImportQueue]=useState([])
 const [importBatchTotal,setImportBatchTotal]=useState(0)
 const refresh=()=>fetch('/api/surveys',{signal:AbortSignal.timeout(10000)}).then(async response=>{if(response.status===401){window.dispatchEvent(new Event('valor360:unauthorized'));throw new Error('Sessão expirada.')}const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error||'Não foi possível atualizar os convites.');return payload}).then(data=>{setSurveys(Array.isArray(data)?data:[]);setError('')}).catch(exception=>{if(!/sessão expirada/i.test(exception.message))setError(exception.name==='TimeoutError'?'A lista de convites demorou para responder.':exception.message)})
 useEffect(()=>{refresh()},[])
 const stats=useMemo(()=>({total:surveys.length,pending:surveys.filter(item=>item.status==='aguardando').length,answered:surveys.filter(item=>item.status!=='aguardando').length,irt:Math.round(surveys.filter(item=>item.result).reduce((sum,item)=>sum+Number(item.result.irt||0),0)/Math.max(surveys.filter(item=>item.result).length,1))}),[surveys])
 const createInvitation=async()=>{
  setLoading(true);setError('')
  try{
   const response=await fetch('/api/surveys/invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({producerName:producerName.trim(),consultantName:'Equipe VALOR 360'}),signal:AbortSignal.timeout(10000)})
   if(response.status===401){window.dispatchEvent(new Event('valor360:unauthorized'));throw new Error('Sua sessão expirou.')}
   const invitation=await response.json().catch(()=>({}));if(!response.ok)throw new Error(invitation.error||'Não foi possível criar o convite agora.');const link=`${window.location.origin}/?responder=${invitation.token}`
   setCreated({...invitation,link});setProducerName('');refresh();onNotify?.('Link do Produtor 360 criado com sucesso.')
  }catch(exception){setError(exception.message)}finally{setLoading(false)}
 }
 const copyLink=async link=>{try{await navigator.clipboard.writeText(link);onNotify?.('Link copiado. Pronto para enviar ao produtor.')}catch{setError('O navegador não permitiu copiar o link. Selecione-o manualmente.')}}
 const shareWhatsApp=invitation=>{const text=`Olá${invitation.producerName?`, ${invitation.producerName.split(' ')[0]}`:''}! Preparei um questionário rápido do Produtor 360 para entendermos melhor suas preferências e gerar mais valor para a propriedade. Leva de 5 a 7 minutos: ${invitation.link||`${window.location.origin}/?responder=${invitation.token}`}`;window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}
 const integrate=async survey=>{
  if(!survey.result)return
  try{const response=await fetch(`/api/surveys/${survey.token}/integrate`,{method:'POST',signal:AbortSignal.timeout(10000)});if(response.status===401){window.dispatchEvent(new Event('valor360:unauthorized'));return}const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Não foi possível incorporar esta resposta.');onCreate?.({...survey.result,id:survey.result.id||`${survey.token}-${Date.now()}`});refresh();onNotify?.(`${survey.result.name} incorporado ao Cliente 360.`)}catch(exception){setError(exception.name==='TimeoutError'?'A incorporação demorou além do limite.':exception.message)}
 }
 const assistedSubmit=async payload=>{const response=await fetch('/api/clients/from-survey',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers:payload.answers}),signal:AbortSignal.timeout(10000)});if(response.status===401){window.dispatchEvent(new Event('valor360:unauthorized'));throw new Error('Sua sessão expirou.')}const saved=await response.json().catch(()=>({}));if(!response.ok)throw new Error(saved.error||'Não foi possível salvar o perfil agora.');const client=saved.client||payload.result;onCreate?.(client);const next=importQueue[0];if(next){setImportQueue(current=>current.slice(1));setImportedAnswers(next.answers);setAssistedResult(null);onNotify?.(`${client.name} salvo. Revise agora ${next.producerName||'o próximo perfil'}.`);window.scrollTo({top:0,behavior:'smooth'})}else{setAssistedResult(client);onNotify?.(importBatchTotal>1?`${importBatchTotal} perfis revisados e salvos na carteira.`:'Preferências compiladas e salvas na carteira.')}}
 const reviewImported=records=>{const list=(Array.isArray(records)?records:[{answers:records}]).filter(item=>item?.answers&&typeof item.answers==='object');if(!list.length){setError('Nenhum perfil válido foi encontrado para revisão.');return}setImportedAnswers(list[0].answers);setImportQueue(list.slice(1));setImportBatchTotal(list.length);setAssistedResult(null);setMode('assistida');window.scrollTo({top:0,behavior:'smooth'})}
 return <div className="page-stack producer-lab">
  <section className="producer-hero"><div className="producer-hero-copy"><span className="eyebrow">PRODUTOR 360 • PREFERÊNCIAS DECLARADAS</span><h2>Contexto para adaptar o atendimento — sem rotular a pessoa.</h2><p>Convide, reconheça respostas externas e acompanhe preferências que podem mudar conforme a decisão.</p><div className="producer-hero-actions"><button onClick={()=>setMode('central')}><Link2/>Criar link inteligente</button><button onClick={()=>setMode('importar')}><Sparkles/>Importar respostas</button></div></div><div className="dna-visual"><div className="dna-core"><Sparkles/><b>360°</b><span>visão viva</span></div>{['Preferência','IRT','NPS','Valor','Canal'].map((label,index)=><i key={label} style={{'--i':index}}><span>{label}</span></i>)}</div></section>
  <nav className="producer-tabs"><button className={mode==='central'?'active':''} onClick={()=>setMode('central')}><Inbox/>Central de respostas</button><button className={mode==='importar'?'active':''} onClick={()=>setMode('importar')}><Sparkles/>Importar arquivo</button><button className={mode==='assistida'?'active':''} onClick={()=>{setImportedAnswers({});setImportQueue([]);setImportBatchTotal(0);setAssistedResult(null);setMode('assistida')}}><ClipboardCheck/>Aplicação assistida</button></nav>
  {mode==='central'&&<>
   <section className="survey-stat-grid"><article><span><Link2/></span><small>CONVITES CRIADOS</small><b>{stats.total}</b><p>links individuais</p></article><article><span><UsersRound/></span><small>AGUARDANDO</small><b>{stats.pending}</b><p>produtores a responder</p></article><article><span><UserRoundCheck/></span><small>RECEBIDOS</small><b>{stats.answered}</b><p>respostas completas</p></article><article><span><BarChart3/></span><small>IRT MÉDIO</small><b>{stats.irt||'—'}</b><p>respostas recebidas</p></article></section>
   <section className="invite-composer"><div className="invite-copy"><span className="eyebrow">NOVO CONVITE</span><h2>Crie uma experiência individual.</h2><p>Cada produtor recebe um link único, pensado para responder pelo celular.</p></div><div className="invite-form"><label>Nome do produtor <span>opcional</span><input value={producerName} onChange={event=>setProducerName(event.target.value)} placeholder="Ex.: João da Silva"/></label><button disabled={loading} onClick={createInvitation}><Plus/>{loading?'Criando...':'Gerar link do questionário'}</button></div></section>
   {created&&<section className="fresh-link"><div><span><Check/></span><div><small>CONVITE PRONTO</small><b>{created.producerName||'Questionário aberto'}</b><p>{created.link}</p></div></div><div><button onClick={()=>copyLink(created.link)}><Copy/>Copiar link</button><button className="whatsapp-btn" onClick={()=>shareWhatsApp(created)}><MessageCircle/>Enviar pelo WhatsApp</button></div></section>}
   {error&&<div className="form-error" role="alert">{error}</div>}
   <section className="response-inbox panel"><div className="panel-head"><div><span className="eyebrow">CAIXA DE ENTRADA</span><h3>Respostas e convites</h3></div><button onClick={refresh}>Atualizar</button></div>{!surveys.length?<div className="inbox-empty"><Inbox/><h3>Os próximos perfis aparecerão aqui.</h3><p>Crie o primeiro link e envie ao produtor.</p></div>:<div className="survey-list">{surveys.map(survey=><article key={survey.token}><div className={`survey-status ${survey.status}`}><span/></div><div className="survey-person"><b>{survey.result?.name||survey.producerName||'Questionário aberto'}</b><small>Criado em {new Date(survey.createdAt).toLocaleDateString('pt-BR')} • {statusLabel(survey.status)}</small></div>{survey.result&&<div className="survey-profile"><span>{survey.result.primaryProfile}</span><b>IRT {survey.result.irt}</b></div>}<div className="survey-row-actions"><button title="Copiar link" onClick={()=>copyLink(`${window.location.origin}/?responder=${survey.token}`)}><Copy/></button>{survey.status==='respondido'&&<button className="integrate-btn" onClick={()=>integrate(survey)}>Incorporar ao 360 <ArrowRight/></button>}{survey.status==='integrado'&&<button className="integrated" onClick={()=>onOpen?.(survey.result)}><Check/>Ver perfil</button>}</div></article>)}</div>}</section>
  </>}
  {mode==='importar'&&<QuestionnaireImport onReview={reviewImported}/>}
  {mode==='assistida'&&!assistedResult&&importBatchTotal>1&&<div className="import-batch-progress"><span>REVISÃO EM LOTE</span><b>Perfil {importBatchTotal-importQueue.length} de {importBatchTotal}</b><small>Cada produtor é validado e salvo individualmente.</small></div>}
  {mode==='assistida'&&!assistedResult&&<SurveyForm key={JSON.stringify(importedAnswers)} initialAnswers={importedAnswers} embedded onSubmit={assistedSubmit} submitLabel={importQueue.length?'Salvar e revisar próximo':'Compilar perfil'}/>}
  {mode==='assistida'&&assistedResult&&<section className="profile-result"><div className="result-glow"><Sparkles/></div><span className="eyebrow">PREFERÊNCIAS COMPILADAS</span><h2>{assistedResult.name}</h2><p>As respostas geram tags de compatibilidade derivadas do que foi declarado; não são diagnóstico psicológico nem substituem o contexto da decisão.</p><div className="result-profiles"><div><small>TAG DERIVADA PRINCIPAL</small><b>{assistedResult.primaryProfile}</b></div><div><small>TAG DERIVADA SECUNDÁRIA</small><b>{assistedResult.secondaryProfile}</b></div><div><small>IRT</small><b>{assistedResult.irt}</b></div><div><small>NPS</small><b>{assistedResult.nps}</b></div></div><button className="primary-btn" onClick={()=>onOpen?.(assistedResult)}>Abrir Cliente 360 <ArrowRight/></button></section>}
 </div>
}
