import React,{useEffect,useState} from 'react'
import {Check,Copy,KeyRound,LoaderCircle,Pencil,Plus,RefreshCw,ShieldCheck,UserCheck,UserX,UsersRound} from 'lucide-react'

const roleLabels={admin:'Administrador',manager:'Gestor',consultant:'Consultor',technical_reviewer:'Revisor técnico'}
const emptyForm={name:'',email:'',role:'consultant'}
const accessUserName=user=>String(user?.name||user?.displayName||user?.email||'Usuário').trim()||'Usuário'
const accessUserInitials=user=>accessUserName(user).split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()
const accessApi='/api/portfolio-admin/users'

export default function AccessManagement({currentUser,onNotify}){
 const [users,setUsers]=useState([])
 const [form,setForm]=useState(emptyForm)
 const [editing,setEditing]=useState(null)
 const [draft,setDraft]=useState(null)
 const [temporary,setTemporary]=useState(null)
 const [loading,setLoading]=useState(true)
 const [saving,setSaving]=useState(false)
 const [error,setError]=useState('')
 const load=()=>{setLoading(true);setError('');return fetch(accessApi,{signal:AbortSignal.timeout(10000)}).then(async response=>{if(response.status===401){window.dispatchEvent(new Event('valor360:unauthorized'));throw new Error('Sua sessão expirou.')}const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Não foi possível carregar os acessos.');setUsers(payload.users||[])}).catch(exception=>setError(exception.message)).finally(()=>setLoading(false))}
 useEffect(()=>{if(currentUser?.role==='admin')load()},[currentUser?.role])
 if(currentUser?.role!=='admin'||currentUser?.demo)return null
 const create=async event=>{event.preventDefault();setSaving(true);setError('');try{const response=await fetch(accessApi,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form),signal:AbortSignal.timeout(15000)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Não foi possível liberar o acesso.');setTemporary({name:payload.user.name,email:payload.user.email,password:payload.temporaryPassword});setForm(emptyForm);await load();onNotify?.('Login criado com carteira zerada.')}catch(exception){setError(exception.message)}finally{setSaving(false)}}
 const update=async input=>{setSaving(true);setError('');try{const response=await fetch(accessApi,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(input),signal:AbortSignal.timeout(15000)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Não foi possível atualizar o acesso.');setUsers(current=>current.map(user=>user.id===payload.user.id?{...user,...payload.user}:user));setEditing(null);setDraft(null);onNotify?.('Acesso atualizado.')}catch(exception){setError(exception.message)}finally{setSaving(false)}}
 const reset=async user=>{if(!window.confirm(`Gerar uma nova senha temporária para ${accessUserName(user)}? A sessão atual desse login será encerrada.`))return;setSaving(true);setError('');try{const response=await fetch(`${accessApi}/reset-password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:user.id}),signal:AbortSignal.timeout(15000)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Não foi possível redefinir a senha.');setTemporary({name:accessUserName(payload.user),email:payload.user.email,password:payload.temporaryPassword});setUsers(current=>current.map(item=>item.id===payload.user.id?{...item,...payload.user}:item));onNotify?.('Nova senha temporária gerada.')}catch(exception){setError(exception.message)}finally{setSaving(false)}}
 const copy=async value=>{try{await navigator.clipboard.writeText(value);onNotify?.('Senha temporária copiada.')}catch{setError('O navegador não permitiu copiar. Selecione a senha manualmente.')}}
 return <section className="access-management" aria-labelledby="access-management-title">
  <div className="access-management-head"><div><span className="access-management-icon"><UsersRound/></span><div><span className="eyebrow">LIBERAÇÃO DE CLIENTES</span><h3 id="access-management-title">Acessos e carteiras individuais</h3><p>Cada login novo começa com zero produtores e enxerga somente o que cadastrar, importar ou sincronizar no próprio espaço.</p></div></div><button type="button" onClick={load} disabled={loading} aria-label="Atualizar acessos">{loading?<LoaderCircle className="val-spinner"/>:<RefreshCw/>}Atualizar</button></div>
  <form className="access-create-form" onSubmit={create}><label>Nome do usuário<input required value={form.name} onChange={event=>setForm(current=>({...current,name:event.target.value}))} placeholder="Ex.: Consultor Regional"/></label><label>E-mail de login<input required type="email" value={form.email} onChange={event=>setForm(current=>({...current,email:event.target.value}))} placeholder="nome@empresa.com"/></label><label>Perfil<select value={form.role} onChange={event=>setForm(current=>({...current,role:event.target.value}))}><option value="consultant">Consultor</option><option value="manager">Gestor</option><option value="technical_reviewer">Revisor técnico</option></select></label><button className="primary-btn" disabled={saving}><Plus/>{saving?'Liberando…':'Liberar novo login'}</button></form>
  {temporary&&<div className="temporary-access" role="status"><ShieldCheck/><div><small>SENHA TEMPORÁRIA — EXIBIDA UMA VEZ</small><b>{temporary.name} • {temporary.email}</b><code>{temporary.password}</code><span>Envie por um canal seguro. A troca é obrigatória no primeiro acesso.</span></div><button type="button" onClick={()=>copy(temporary.password)}><Copy/>Copiar senha</button><button type="button" className="temporary-close" onClick={()=>setTemporary(null)} aria-label="Fechar"><Check/></button></div>}
  {error&&<div className="form-error" role="alert">{error}</div>}
  <div className="access-user-list">{loading&&!users.length?<div className="access-loading"><LoaderCircle className="val-spinner"/>Carregando acessos…</div>:users.map(user=><article key={user.id} className={user.status==='blocked'?'is-blocked':''}>
   {editing===user.id?<form className="access-edit-row" onSubmit={event=>{event.preventDefault();update(draft)}}><label>Nome<input required value={draft.name} onChange={event=>setDraft(current=>({...current,name:event.target.value}))}/></label><label>E-mail<input required type="email" disabled={user.id===currentUser.id} value={draft.email} onChange={event=>setDraft(current=>({...current,email:event.target.value}))}/></label><label>Perfil<select value={draft.role} disabled={user.id===currentUser.id} onChange={event=>setDraft(current=>({...current,role:event.target.value}))}><option value="admin">Administrador</option><option value="manager">Gestor</option><option value="consultant">Consultor</option><option value="technical_reviewer">Revisor técnico</option></select></label><div><button className="primary-btn" disabled={saving}><Check/>Salvar</button><button type="button" className="ghost-btn" onClick={()=>{setEditing(null);setDraft(null)}}>Cancelar</button></div></form>:<><div className="access-user-main"><span className="access-avatar">{accessUserInitials(user)}</span><div><b>{accessUserName(user)}</b><small>{user.email}</small></div></div><div className="access-user-facts"><span>{roleLabels[user.role]||user.role}</span><span><b>{user.producerCount||0}</b> produtores</span><span className={user.status==='active'?'is-active':''}>{user.status==='active'?'Liberado':'Bloqueado'}</span>{user.mustChangePassword&&<span>Troca de senha pendente</span>}</div><div className="access-user-actions"><button type="button" onClick={()=>{setEditing(user.id);setDraft({id:user.id,name:accessUserName(user),email:user.email,role:user.role,status:user.status})}}><Pencil/>Editar</button>{user.id!==currentUser.id&&<button type="button" onClick={()=>reset(user)} disabled={saving}><KeyRound/>Nova senha</button>}{user.id!==currentUser.id&&<button type="button" className={user.status==='active'?'danger-text':''} onClick={()=>update({id:user.id,status:user.status==='active'?'blocked':'active'})}>{user.status==='active'?<UserX/>:<UserCheck/>}{user.status==='active'?'Bloquear':'Liberar'}</button>}</div></>}
  </article>)}</div>
 </section>
}
