import {AgronomicDecisionCard} from './AgronomicDecisionCard'
import React,{useEffect,useMemo,useState} from 'react'
import {fetchJsonResource} from '../hooks/useAsyncResource'
import SatelliteMap from './map/SatelliteMap'
import './AgroTerritoryPanel.css'
export default function AgroTerritoryPanel({clientId='',scope='',map=false}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[offline,setOffline]=useState(typeof navigator!=='undefined'&&!navigator.onLine),[revision,setRevision]=useState(0),[property,setProperty]=useState(''),[field,setField]=useState(''),[season,setSeason]=useState(''),[showFields,setShowFields]=useState(true)
 const key=`${scope}:${clientId}:${revision}`
 useEffect(()=>{const controller=new AbortController();let active=true;setData(null);setError('');setProperty('');setField('');setSeason('')
  fetchJsonResource(`/api/agro-geo${clientId?'?clientId='+encodeURIComponent(clientId):''}`,{signal:controller.signal,timeoutMs:30000}).then(value=>{if(active)setData({key,value})}).catch(e=>{if(active&&e.name!=='AbortError')setError('UNAVAILABLE — leitura territorial indisponível.')})
  return()=>{active=false;controller.abort()}
 },[key,clientId])
 useEffect(()=>{const update=()=>setOffline(!navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[])
 const result=data?.key===key?data.value:null,properties=result?.territories.flatMap(t=>t.properties.map(p=>({...p,producer:t.producer})))||[],fields=properties.filter(p=>!property||p.id===property).flatMap(p=>p.fields.map(f=>({...f,property:p}))),filtered=fields.filter(f=>(!field||f.id===field)&&(!season||f.season===season))
 const polygons=useMemo(()=>showFields?filtered.flatMap(f=>(f.geometry?.type==='Polygon'?[f.geometry.coordinates]:f.geometry?.type==='MultiPolygon'?f.geometry.coordinates:[]).map((rings,i)=>({id:`${f.id}:${i}`,points:rings[0].map(([lng,lat])=>({lng,lat})),holes:rings.slice(1).map(r=>r.map(([lng,lat])=>({lng,lat}))),color:f.status==='VALID'?'#00c896':'#f5b94c',label:f.name,labelPermanent:f.id===field,onClick:()=>setField(f.id)}))):[],[result,property,field,season,showFields])
 if(result&&!result.enabled)return null
 const cards=(result?.cards||[]).filter(c=>(!property||c.property.id===property)&&(!field||c.field.id===field)&&(!season||c.season===season)).slice(0,5)
 return <section className="agro-territory" aria-label="Inteligência territorial"><header><h2>Talhões que precisam de atenção</h2><button onClick={()=>setRevision(n=>n+1)}>Atualizar território</button></header>{offline&&<p role="status">{result?'STALE_CACHE — última leitura desta sessão.':'OFFLINE — sem leitura disponível.'}</p>}{error?<p role="alert">{error}</p>:!result?<p role="status">Consultando evidências territoriais…</p>:<><p>{properties.length} propriedades · {fields.length} talhões · {result.territories.reduce((n,t)=>n+t.unlinked.length,0)} registros sem vínculo. Clima atual: fonte ainda não conectada.</p>{map&&<><div className="agro-territory-filters"><label>Propriedade<select value={property} onChange={e=>{setProperty(e.target.value);setField('')}}><option value="">Todas</option>{properties.map(p=><option key={p.id} value={p.id}>{p.producer.name} · {p.name}</option>)}</select></label><label>Talhão<select value={field} onChange={e=>setField(e.target.value)}><option value="">Todos</option>{fields.map(f=><option key={f.id} value={f.id}>{f.name} · {f.crop||'Cultura desconhecida'}</option>)}</select></label><label>Safra<select value={season} onChange={e=>setSeason(e.target.value)}><option value="">Todas</option>{[...new Set(fields.map(f=>f.season).filter(Boolean))].map(s=><option key={s}>{s}</option>)}</select></label><label><input type="checkbox" checked={showFields} onChange={e=>setShowFields(e.target.checked)}/>Contornos disponíveis</label></div>{(polygons.length||properties.some(p=>p.metadata?.location))&&!offline?<SatelliteMap viewKey={`${key}:${property}:${field}:${season}`} polygons={polygons} pins={properties.filter(p=>!property||p.id===property).filter(p=>p.metadata?.location).map((p,index)=>({id:p.id,propertyId:p.id,...p.metadata.location,label:String(index+1),title:p.name,caption:p.name,selected:p.id===property}))} onPinClick={pin=>{setProperty(pin.id);setField('')}} height={360} fit label="Mapa territorial governado" clientId={clientId||null}/>:<p>Mapa UNAVAILABLE — selecione um talhão com geometria ou restabeleça a rede.</p>}<p aria-label="Legenda">Verde: geometria plausível · Amarelo: revisão necessária. Cadastros de referência não comprovam vínculo ou titularidade.</p></>}{cards.length?<div className="agro-territory-grid">{cards.map(c=><AgronomicDecisionCard key={c.id} card={c} onFocus={map?setField:null}/>)}</div>:<p>Sem sinal agronômico vinculado suficiente para priorização.</p>}</>}</section>
}
