import GeoReviewQueue from './GeoReviewQueue'
import React,{useEffect,useState} from 'react'
import {fetchJsonResource,requestJsonResource} from '../hooks/useAsyncResource'
import {DecisionCard} from './DecisionPanel'

export default function DecisionGovernance(){
 const [registry,setRegistry]=useState(null),[queue,setQueue]=useState([]),[selected,setSelected]=useState(null),[reason,setReason]=useState(''),[resolution,setResolution]=useState('RESOLVED'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[change,setChange]=useState(null)
 useEffect(()=>{let active=true;const controller=new AbortController()
  Promise.all([fetchJsonResource('/api/decisions/registry',{signal:controller.signal}),fetchJsonResource('/api/decisions/reviews',{signal:controller.signal})]).then(([r,q])=>{if(active){setRegistry(r);setQueue(q.items)}}).catch(e=>{if(active&&e.name!=='AbortError')setNotice(e.message)})
  return()=>{active=false;controller.abort()}
 },[revision])
 const open=async item=>{try{setSelected({item,...await fetchJsonResource(`/api/decisions/cards/${item.card_id}`)});setReason('');setNotice('')}catch(e){setNotice(e.message)}}
 const resolve=async()=>{setBusy(true);try{await requestJsonResource(`/api/decisions/cards/${selected.item.card_id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:resolution,reason})});setSelected(null);setRevision(x=>x+1);setNotice('Revisão registrada. A evidência e os dados do produtor foram preservados.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 const configure=async()=>{setBusy(true);try{await requestJsonResource('/api/decisions/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...change,expectedRevision:registry.revision,reason})});setChange(null);setRevision(x=>x+1);setNotice('Versão de governança registrada.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 return <section className="nba-governance" aria-label="Governança de decisões"><h2>Governança de decisões</h2><p>Revisões, versões e capacidades disponíveis para o seu acesso.</p>{notice&&<p role="status">{notice}</p>}
  <GeoReviewQueue/>
  <details><summary>Fila de revisão ({queue.filter(x=>x.status==='PENDING').length} pendentes)</summary><p>Até 200 registros mais recentes da sua carteira.</p>{queue.length?<ul>{queue.map(item=><li key={item.id}><button onClick={()=>open(item)}>{item.producer.name} · {item.status}</button> {item.reasons.join(', ')}</li>)}</ul>:<p>Nenhuma revisão registrada.</p>}</details>
  {selected&&<div><DecisionCard card={selected.card} readOnly/><p>Estado: {selected.item.status}</p>{selected.item.status==='PENDING'&&<><label>Resultado<select value={resolution} onChange={e=>setResolution(e.target.value)}><option value="RESOLVED">Resolvido</option><option value="APPROVED">Aprovado para acompanhamento</option><option value="REJECTED">Descartado</option></select></label><label>Justificativa obrigatória<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000}/></label><p>A revisão não aprova prescrição nem altera identidade, evidência ou CRM.</p><button disabled={busy||!reason.trim()} onClick={resolve}>Confirmar revisão</button></>}<button onClick={()=>setSelected(null)}>Fechar revisão</button></div>}
  {registry&&<><details><summary>Capacidades e políticas · revisão {registry.revision}</summary><div className="nba-flags">{Object.entries(registry.flags).map(([key,value])=><label key={key}><input type="checkbox" checked={value} disabled={!registry.mutable} onChange={e=>{setChange({flags:{[key]:e.target.checked}});setReason('')}}/>{key} · {value?'Ativa':'Desativada'}</label>)}</div><p>Política: {registry.policy_version}</p>{registry.mutable&&<><button onClick={()=>{setChange({policyVersion:registry.policy_version==='val.decision-scoring.v1'?'val.decision-scoring.conservative.v1':'val.decision-scoring.v1'});setReason('')}}>Preparar troca de política</button>{registry.history.filter(h=>h.revision<registry.revision).map(h=><button key={h.revision} onClick={()=>{setChange({rollbackRevision:h.revision});setReason('')}}>Restaurar revisão {h.revision}</button>)}</>}<p>Reversões criam uma nova versão e conservam o histórico.</p></details>
   {change&&<div className="nba-confirm"><h3>Confirmar alteração de governança</h3><p>{change.rollbackRevision!==undefined?`Restaurar revisão ${change.rollbackRevision}`:change.policyVersion||Object.entries(change.flags).map(([k,v])=>`${k}: ${v?'ativar':'desativar'}`).join(', ')}</p><textarea aria-label="Motivo da alteração" value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/><button disabled={busy||!reason.trim()} onClick={configure}>Confirmar alteração</button><button disabled={busy} onClick={()=>setChange(null)}>Cancelar</button></div>}
   {['prompts','models','policies'].map(kind=><details key={kind}><summary>{kind==='prompts'?'Prompts':kind==='models'?'Modelos por capacidade':'Políticas versionadas'}</summary><ul>{registry.registry[kind].map((item,index)=><li key={index}><b>{item.prompt_id||item.capability||item.policy_id}</b><p>{item.purpose||item.model||item.source}</p><small>Versão: {item.version} · estado: {item.status} · reversão: {item.rollback_version}</small>{item.approval_status&&<p>Homologação de release pendente.</p>}</li>)}</ul></details>)}
   {registry.runtime_registry_drift&&<p role="alert">O inventário do ambiente mudou em relação ao registro. Revise as versões antes de homologar.</p>}
  </>}
 </section>
}
