import React,{useEffect,useState} from 'react'
import './LearningCenter.css'
const tabs=[['summary','Resumo'],['candidates','Candidatos'],['patterns','Padrões'],['evidence','Evidências'],['contrary','Contradições'],['datasets','Datasets'],['shadow','Shadow mode'],['promotions','Promoções'],['drift','Drift'],['history','Histórico'],['rollback_history','Rollbacks'],['knowledge','O que mudou?'],['controls','Políticas offline']]
const pretty=x=>JSON.stringify(x,null,2)
async function request(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const value=await r.json();if(!r.ok)throw Error(value.error||'Não foi possível concluir a operação.');return value}
export default function LearningCenter({currentUser}){
 const [tab,setTab]=useState('summary'),[state,setState]=useState({data:null,error:''}),[offset,setOffset]=useState(0),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false)
 const allowed=['admin','technical_reviewer','manager','bi_viewer'].includes(currentUser?.role)
 useEffect(()=>{if(!allowed)return;let active=true;setState({data:null,error:''});request(`/api/learning/center?limit=30&offset=${offset}`).then(data=>{if(active)setState({data,error:''})}).catch(e=>{if(active)setState({data:null,error:e.message})});return()=>{active=false}},[allowed,offset,revision,currentUser?.id])
 const run=async(path,data)=>{setBusy(true);try{await request(path,data);setRevision(r=>r+1)}catch(e){setState(s=>({...s,error:e.message}))}finally{setBusy(false)}}
 if(!allowed)return null
 const data=state.data,items=data?.[tab]||[]
 return <section className="learning-center" aria-label="Central de Aprendizado">
 <header><h2>Central de Aprendizado</h2><p>Hipóteses e padrões candidatos. Revisão humana e evidências antes de qualquer promoção.</p></header>
 <nav aria-label="Seções do aprendizado">{tabs.map(([id,label])=><button key={id} type="button" aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {state.error&&<p role="alert">{state.error}</p>}{!data&&!state.error&&<p role="status">Carregando…</p>}
 {data&&tab==='summary'&&<><h3>O que aprendemos?</h3><p>{data.summary.visible_candidates} candidatos nesta página; {data.summary.review_pending} aguardam revisão. {data.summary.sample_note}</p><p>Amostra insuficiente para generalizar. O ranking shadow não altera o ranking operacional.</p></>}
 {data&&['evidence','contrary'].includes(tab)&&(data.candidates||[]).map(c=><article key={c.id}><h3>{c.hypothesis}</h3><pre>{pretty(tab==='contrary'?c.contrary_evidence:c.supporting_evidence)}</pre></article>)}
 {data&&tab==='candidates'&&items.map(c=><article key={c.id}><h3>{c.hypothesis}</h3><p>{c.status} · {c.learning_metadata?.classification||'ACCOUNT_OBSERVATION'}</p><p>{c.supporting_evidence.length} evidências favoráveis / {c.supporting_evidence.length+c.contrary_evidence.length} observações; {c.contrary_evidence.length} contrárias.</p><details><summary>Escopo, origem e evidências</summary><pre>{pretty({scope:c.scope,confidence:c.confidence,origin:c.source_outcome_id,metadata:c.learning_metadata,supporting:c.supporting_evidence,contrary:c.contrary_evidence})}</pre></details><ReviewForm row={c} kind="candidates" busy={busy} run={run}/></article>)}
 {data&&tab==='datasets'&&currentUser.role==='admin'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run('/api/learning/datasets',{period_start:new Date(f.get('start')).toISOString(),period_end:new Date(f.get('end')).toISOString()})}}><h3>Preparar dataset offline</h3><label>Início<input required name="start" type="datetime-local"/></label><label>Fim<input required name="end" type="datetime-local"/></label><button disabled={busy}>Criar dataset</button></form>}
 {data&&tab==='promotions'&&['admin','technical_reviewer'].includes(currentUser.role)&&<ProposalForm candidates={data.candidates} busy={busy} run={run}/>}
 {data&&tab==='drift'&&currentUser.role==='admin'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run('/api/learning/drift',{previous_id:f.get('previous'),current_id:f.get('current')})}}><h3>Comparar períodos</h3><label>Dataset anterior<input required name="previous"/></label><label>Dataset posterior<input required name="current"/></label><button disabled={busy}>Verificar drift</button></form>}
 {data&&tab==='controls'&&currentUser.role==='admin'&&<ControlForm busy={busy} run={run}/>}
 {data&&tab==='controls'&&items.filter(c=>c.status==='DRAFT').map(c=><article key={'review-'+c.id}><h3>Revisar {c.kind} · {c.version}</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(`/api/learning/controls/${c.id}/review`,{status:f.get('status'),reason:f.get('reason'),evidence_reviewed:String(f.get('evidence')).split(',').map(x=>x.trim()).filter(Boolean),contrary_evidence_reviewed:String(f.get('contrary')).split(',').map(x=>x.trim()).filter(Boolean)})}}><label>Decisão<select name="status"><option>APPROVED</option><option>REJECTED</option></select></label><label>Justificativa da política<textarea required name="reason"/></label><label>Evidências revisadas<input required name="evidence"/></label><label>Evidências contrárias revisadas<input name="contrary"/></label><p>O revisor deve ser diferente do proponente.</p><button disabled={busy}>Registrar revisão da política</button></form></article>)}
 {data&&tab==='promotions'&&items.map(p=><article key={p.id}><h3>{p.kind} · {p.status}</h3><p>{p.payload.reason}</p><details><summary>Versões, evidências e rollback</summary><pre>{pretty(p.payload)}</pre></details><ReviewForm row={p} kind="promotions" busy={busy} run={run}/></article>)}
 {data&&!['summary','candidates','promotions','evidence','contrary'].includes(tab)&&items.map((item,i)=><article key={item.id||i}><h3>{item.kind||item.action||item.title||'Registro governado'}</h3><pre>{pretty(item.payload||item)}</pre>{tab==='datasets'&&currentUser.role==='admin'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run('/api/learning/shadow',{dataset_id:item.id,cutoff:new Date(f.get('cutoff')).toISOString()})}}><label>Corte temporal<input required type="datetime-local" name="cutoff"/></label><button disabled={busy}>Avaliar em shadow</button></form>}</article>)}
 {data&&tab!=='summary'&&!items.length&&!['evidence','contrary'].includes(tab)&&<p>Nenhum registro autorizado nesta página.</p>}
 <footer><button onClick={()=>setOffset(n=>Math.max(0,n-30))} disabled={!offset}>Anterior</button><span>Página {Math.floor(offset/30)+1}</span><button onClick={()=>setOffset(n=>n+30)} disabled={!data}>Próxima</button></footer>
 </section>
}
function ReviewForm({row,kind,busy,run}){
 const candidate=kind==='candidates',options=candidate?{CANDIDATE:['UNDER_REVIEW','REJECTED','EXPIRED'],UNDER_REVIEW:['APPROVED','REJECTED','EXPIRED'],APPROVED:['UNDER_REVIEW','EXPIRED']}:{DRAFT:['UNDER_REVIEW','REJECTED'],UNDER_REVIEW:['APPROVED','REJECTED'],APPROVED:['PUBLISHED','REJECTED'],PUBLISHED:['ROLLED_BACK','SUPERSEDED']}
 if(!options[row.status])return null
 return <details><summary>Revisão humana</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(`/api/learning/${kind}/${row.id}/review`,{status:f.get('status'),reason:f.get('reason'),expected_status:row.status,expected_revision:row.revision,evidence_reviewed:String(f.get('evidence')).split(',').map(x=>x.trim()).filter(Boolean),contrary_evidence_reviewed:String(f.get('contrary')).split(',').map(x=>x.trim()).filter(Boolean)})}}><label>Decisão<select name="status">{options[row.status].map(s=><option key={s}>{s}</option>)}</select></label><label>Justificativa<textarea name="reason" required/></label><label>IDs das evidências revisadas<input name="evidence" required/></label><label>IDs das evidências contrárias revisadas<input name="contrary"/></label><button disabled={busy}>Registrar revisão</button></form></details>
}

function ProposalForm({candidates,busy,run}){
 return <details><summary>Propor mudança versionada</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),input=Object.fromEntries(f);run('/api/learning/promotions',input)}}><label>Candidato aprovado<select required name="candidate_id"><option value="">Selecione</option>{candidates.filter(c=>c.status==='APPROVED').map(c=><option value={c.id} key={c.id}>{c.hypothesis}</option>)}</select></label><label>Tipo<select name="kind">{['PROMPT','POLICY','WEIGHT','MODEL','QUESTION','RULE'].map(k=><option key={k}>{k}</option>)}</select></label><label>Identificador do alvo<input required name="target_id"/></label><label>Versão atual<input required name="current_version"/></label><label>Versão candidata<input required name="candidate_version"/></label><label>Motivo<textarea required name="reason"/></label><label>Efeito esperado<textarea required name="expected_effect"/></label><label>Risco<select name="risk"><option>LOW</option><option>HIGH</option></select></label><label>Alteração proposta<textarea required name="diff"/></label><label>Avaliação offline<input name="evaluation_id"/></label><label>Relatório de regressão<input name="regression_id"/></label><label>Alvo de rollback<input required name="rollback_target"/></label><label>Revisar em<input required name="review_at" type="date"/></label><label>Válido até<input required name="valid_until" type="date"/></label><p>A proposta não altera o comportamento da VAL.</p><button disabled={busy}>Criar proposta</button></form></details>
}
function ControlForm({busy,run}){
 const [kind,setKind]=useState('SAMPLE')
 return <details><summary>Propor política offline</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),data={kind,version:f.get('version'),reason:f.get('reason')};if(kind==='SAMPLE')data.thresholds={limited:Number(f.get('limited')),sufficient:Number(f.get('sufficient')),strong:Number(f.get('strong'))};else{data.minimum_sample=Number(f.get('minimum'));data.watch=Number(f.get('watch'));data.shift=Number(f.get('shift'))}run('/api/learning/controls',data)}}><label>Política<select value={kind} onChange={e=>setKind(e.target.value)}><option>SAMPLE</option><option>DRIFT</option></select></label><label>Versão da política<input required name="version"/></label><label>Motivo da política<textarea required name="reason"/></label>{(kind==='SAMPLE'?[['limited','Amostra limitada'],['sufficient','Amostra suficiente'],['strong','Amostra forte']]:[['minimum','Amostra mínima'],['watch','Variação para observação (0 a 1)'],['shift','Variação para alerta (0 a 1)']]).map(([name,label])=><label key={name}>{label}<input type="number" step="any" required name={name}/></label>)}<p>Os valores precisam de revisão independente. Nenhum threshold real vem aprovado.</p><button disabled={busy}>Propor política</button></form></details>
}
