import React,{useEffect,useState} from 'react'
import {ChevronsLeft,ChevronsRight,BookOpen,BrainCircuit,Calculator,CalendarDays,ChartNoAxesCombined,FileText,Home,LandPlot,Map,Settings,Sprout,Target,Users,WalletCards,Wheat} from 'lucide-react'
import Logo from './Logo'
export default function ProducerNavigation({tab,onTab,onNavigate,onAsk,user}){
 const [collapsed,setCollapsed]=useState(()=>{try{return localStorage.getItem('valor360-sidebar-collapsed')==='1'}catch{return false}})
 useEffect(()=>{try{localStorage.setItem('valor360-sidebar-collapsed',collapsed?'1':'0')}catch{}},[collapsed])
 const entries=[['overview','Produtor',Users],['commercial','Comercial',Target],['agronomy','Agronomia',Sprout],['grains','Grãos',Wheat],['credit','Crédito',WalletCards],['map','Geo',Map]]
 const nav=(label,Icon,action,active=false)=><button type="button" key={label} onClick={action} title={collapsed?label:undefined} aria-label={label} className={active?'active':''} aria-current={active?'page':undefined}><Icon size={17}/><span>{label}</span></button>
 if(collapsed)return <button type="button" className="sidebar-reopen" aria-label="Expandir navegação" onClick={()=>setCollapsed(false)}><ChevronsRight size={20}/><span>Menu</span></button>
 return <aside className={`p360-navigation${collapsed?' is-collapsed':''}`}><div className="p360-nav-logo"><Logo variant={collapsed?'icon-only':'compact'}/><button type="button" className="p360-nav-collapse" aria-label={collapsed?'Expandir menu lateral':'Recolher menu lateral'} title={collapsed?'Expandir menu':'Recolher menu'} aria-expanded={!collapsed} onClick={()=>setCollapsed(value=>!value)}>{collapsed?<ChevronsRight size={18}/>:<ChevronsLeft size={18}/>}</button></div><nav aria-label="Navegação principal">{nav('Início',Home,()=>onNavigate('dashboard'))}{nav('Clientes',Users,()=>onNavigate('clients'))}{entries.map(([id,label,Icon])=>nav(label,Icon,()=>onTab(id),tab===id))}{nav('Visitas',CalendarDays,()=>onNavigate('visits'))}{nav('Oportunidades',Target,()=>onNavigate('opportunities'))}{nav('Relatórios',ChartNoAxesCombined,()=>onNavigate('reports'))}{nav('IA e Insights',BrainCircuit,onAsk)}</nav><div className="p360-favorites"><small>Favoritos</small><nav aria-label="Ferramentas favoritas">{nav('Produtor 360',Users,()=>onTab('overview'))}{nav('Mapa',LandPlot,()=>onTab('map'))}{nav('Calculadoras',Calculator,()=>onNavigate({page:'agro',tool:'calculadoras'}))}{nav('Manual do Agrônomo',BookOpen,()=>onNavigate({page:'agro',tool:'manual'}))}{nav('Documentos',FileText,()=>onTab('documents'))}</nav></div><footer><span>{(user?.name||user?.email||'V').slice(0,1).toUpperCase()}</span><div><b>{user?.name||user?.email?.split('@')[0]||'Consultor'}</b><small>Minha carteira</small></div><button aria-label="Preferências" onClick={()=>onNavigate('settings')}><Settings size={16}/></button></footer></aside>
}
