import React,{useRef,useState} from 'react'
import {requestJsonResource} from '../hooks/useAsyncResource'
const types=[['NO_DECISION','Sem decisão'],['FOLLOW_UP','Acompanhar'],['WON','Ganho'],['LOST','Perdido'],['PARTIAL','Parcial'],['TECHNICAL_RESULT','Resultado técnico'],['RELATIONSHIP_PROGRESS','Avanço de relacionamento'],['NO_CHANGE','Sem mudança']]
export default function RevenueOutcomeForm({producer,onSaved}){
 const [draft,setDraft]=useState({visit:'',opportunity:'',decision:'',action:'',commitment:'',type:'NO_DECISION',value:'',proof:'',proofType:'CONFIRMED_RECORD',confirmed:false,reason:'',notes:''}),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),id=useRef(null)
 const change=(key,value)=>{id.current=null;setDraft(current=>({...current,[key]:value}))}
 const save=async event=>{event.preventDefault();if(busy)return;setBusy(true);setNotice('');id.current=id.current||crypto.randomUUID();try{await requestJsonResource('/api/v1/outcomes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({outcome_id:id.current,visit_id:draft.visit,action_plan_id:draft.action||null,commitment_id:draft.commitment||null,outcome_type:draft.type,result:{opportunity_id:draft.opportunity||null,decision_card_id:draft.decision||null,value:draft.value===''?null:Number(draft.value),...(draft.type==='LOST'?{loss_reason:draft.reason}:{})},evidence_refs:draft.proof?[{id:draft.proof,type:draft.proofType,confirmed:draft.confirmed}]:[],measured_at:new Date().toISOString(),confidence:.8,notes:draft.notes})});setNotice('Resultado registrado com sua evidência.');onSaved?.()}catch(error){setNotice(error.message)}finally{setBusy(false)}}
 const select=(key,label,options,required=false)=><label>{label}<select required={required} value={draft[key]} onChange={event=>change(key,event.target.value)}><option value="">Não informado</option>{options.map(option=><option key={option.id} value={option.id}>{option.label||option.title||option.objective||option.description||option.id}</option>)}</select></label>
 return <details><summary>Registrar resultado</summary>{!producer.visits?.length?<p>Registre a visita para vincular decisão, compromisso e resultado.</p>:<form onSubmit={save}>{select('visit','Visita',producer.visits,true)}{select('opportunity','Oportunidade',producer.opportunities)}{select('decision','Decisão',producer.decision_cards||[])}{select('action','Plano de ação',producer.action_plans||[])}{select('commitment','Compromisso',producer.commitments||[])}<label>Resultado<select value={draft.type} onChange={event=>change('type',event.target.value)}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{['WON','LOST','PARTIAL'].includes(draft.type)&&<label>Valor registrado (R$)<input type="number" min="0" step="0.01" value={draft.value} onChange={event=>change('value',event.target.value)}/></label>}{draft.type==='LOST'&&<label>Motivo da perda<select required value={draft.reason} onChange={event=>change('reason',event.target.value)}><option value="">Selecione</option>{['PRICE','TIMING','COMPETITOR','TECHNICAL','CREDIT','RELATIONSHIP','OTHER'].map(reason=><option key={reason}>{reason}</option>)}</select></label>}<label>Referência da evidência<input required={['WON','TECHNICAL_RESULT','RELATIONSHIP_PROGRESS'].includes(draft.type)} value={draft.proof} onChange={event=>change('proof',event.target.value)}/></label>{draft.type==='WON'&&<><label>Tipo da prova<select value={draft.proofType} onChange={event=>change('proofType',event.target.value)}>{[['ORDER','Pedido'],['INVOICE','Faturamento'],['COMMERCIAL_EVENT','Evento comercial'],['CONFIRMED_RECORD','Registro confirmado']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><input type="checkbox" required checked={draft.confirmed} onChange={event=>change('confirmed',event.target.checked)}/>Conferi o registro comercial</label></>}<label>O que ocorreu<textarea value={draft.notes} maxLength={4000} onChange={event=>change('notes',event.target.value)}/></label><button disabled={busy}>{busy?'Salvando…':'Registrar resultado'}</button>{notice&&<p role="status">{notice}</p>}</form>}</details>
}
