from pathlib import Path

path=Path('docs/VAL_ENGINE.md')
source=path.read_text()
marker='## Componentes já preparados\n'
section='''## Loop de aprendizado offline\n\nO contrato completo do fechamento do loop está em [`docs/VAL_LEARNING_LOOP.md`](VAL_LEARNING_LOOP.md). O endpoint `POST /api/val/feedback` deve originar o evento lógico `val.feedback.recorded`, ligado por `recommendationId` ao snapshot da recomendação e, depois, aos eventos `business.updated`, `business.closed`, `business.lost`, execução da visita e avanço confirmado de `methodology_state`.\n\nO ranker futuro aprende somente offline e começa em shadow mode. `accepted`, `edited` e `rejected` medem utilidade percebida; `scheduled` e `executed` medem ação; `won`, `lost` e a mudança de etapa medem resultado. Um aceite nunca é tratado como venda e uma recomendação sem feedback permanece sem rótulo.\n\nO painel interno precisa mostrar cobertura, tamanho da amostra, aceite, edição, rejeição, execução, avanço metodológico e acerto de prioridade, sempre com numerador, denominador, período e versão do motor. O Conversion Score continua sendo uma ordenação operacional, não uma probabilidade. Janela de atribuição, K, retenção, amostra mínima e threshold de promoção permanecem decisões de produto pendentes.\n\nNenhum ranker pode liberar revisão técnica, criar oportunidade, alterar preço ou escrever no CRM. Promoção exige avaliação temporal, shadow mode, revisão humana, versão e rollback.\n\n'''
if source.count(marker)!=1:
    raise RuntimeError('marcador de componentes não encontrado de forma única')
path.write_text(source.replace(marker,section+marker,1))

Path('test/learning-loop-docs.test.js').write_text("""import assert from 'node:assert/strict'\nimport {readFileSync} from 'node:fs'\nimport test from 'node:test'\n\nconst read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8')\nconst engine=read('docs/VAL_ENGINE.md')\nconst loop=read('docs/VAL_LEARNING_LOOP.md')\nconst server=read('server.js')\n\ntest('documentação liga feedback, snapshot e resultados posteriores',()=>{\n assert.match(engine,/VAL_LEARNING_LOOP\.md/)\n assert.match(loop,/POST \/api\/val\/feedback/)\n assert.match(loop,/val\.feedback\.recorded/)\n assert.match(loop,/recommendationId/)\n assert.match(loop,/business\.updated/)\n assert.match(loop,/business\.closed/)\n assert.match(loop,/business\.lost/)\n assert.match(loop,/mudança confirmada de `methodology_state`/)\n})\n\ntest('loop distingue reação, execução, progresso e resultado',()=>{\n for(const value of ['accepted','edited','rejected','scheduled','executed','won','lost'])assert.match(loop,new RegExp('`'+value+'`'))\n assert.match(loop,/Um `accepted` não deve ser convertido em `won`/)\n assert.match(loop,/sem rótulo, não rejeitada/)\n assert.match(server,/const feedbackOutcomes=\{used:'executed',adapted:'edited',scheduled:'scheduled',discarded:'rejected',accepted:'accepted',edited:'edited',rejected:'rejected',executed:'executed',won:'won',lost:'lost'\}/)\n})\n\ntest('métricas obrigatórias ficam explícitas e não tratam score como probabilidade',()=>{\n assert.match(loop,/taxa de aceite/)\n assert.match(loop,/taxa de edição/)\n assert.match(loop,/taxa de rejeição/)\n assert.match(loop,/Top-1 progress rate/)\n assert.match(loop,/Precision@K/)\n assert.match(loop,/NDCG@K/)\n assert.match(loop,/Conversion Score atual ordena trabalho; ele não é probabilidade/)\n assert.match(loop,/numerador, denominador, período, versão do motor e tamanho da amostra/)\n})\n\ntest('ranker permanece offline, auditável, seguro e reversível',()=>{\n assert.match(loop,/shadow mode/)\n assert.match(loop,/plano de rollback/)\n assert.match(loop,/não pode[\s\S]*liberar revisão técnica/)\n assert.match(loop,/não usar como alavanca ou feature de persuasão/i)\n assert.match(loop,/atributo sensível/)\n assert.match(loop,/medo, vergonha, culpa/)\n assert.match(loop,/notas livres não entram no treino por padrão/)\n})\n\ntest('thresholds, retenção e janela de atribuição permanecem decisões pendentes',()=>{\n assert.match(loop,/período de retenção do dataset/)\n assert.match(loop,/amostra mínima/)\n assert.match(loop,/janela de atribuição de conversão/)\n assert.match(loop,/valor de K/)\n assert.match(loop,/threshold de ganho/)\n assert.match(loop,/exigem decisão conjunta de Produto, Comercial, Segurança, Jurídico\/LGPD e responsável técnico/)\n})\n""")

Path('scripts/apply-a8.py').unlink(missing_ok=True)
Path('.github/workflows/apply-a8.yml').unlink(missing_ok=True)
print('A8 aplicado com sucesso.')
