import React,{useRef,useState} from 'react'
import {Layers,Upload,Trash2,Search} from 'lucide-react'
import {CADASTRAL_TYPES,CADASTRAL_COLORS,normalizeCadastralGeoJSON,filterCadastral} from '../../lib/cadastral-map'
export default function CadastralLayers({onChange,getPoint,panelOnly=false}){
 const [open,setOpen]=useState(false),[layers,setLayers]=useState([]),[type,setType]=useState('CAR'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const file=useRef(null)
 const [officialStatus,setOfficialStatus]=useState('')
 const consult=async()=>{
  const point=getPoint?.();if(!point?.uf){setError('Selecione um estado ou município antes de consultar os cadastros.');return}
  setBusy(true);setError('');setOfficialStatus('Consultando CAR e SIGEF no ponto central…')
  try{const response=await fetch(`/api/geospatial/official-boundaries?lat=${encodeURIComponent(point.lat)}&lng=${encodeURIComponent(point.lng)}&uf=${encodeURIComponent(point.uf)}`,{signal:AbortSignal.timeout(30000)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Fonte indisponível.');const references=[];const statuses=[];for(const [key,type] of [['car','CAR'],['sigef','SIGEF']]){const result=payload[key];statuses.push(`${type}: ${result?.note||'Fonte indisponível.'}`);if(result?.status==='available'&&result.features?.length){const geojson=normalizeCadastralGeoJSON({type:'FeatureCollection',features:result.features.map(feature=>{const ring=feature.points.map(p=>[p.lng,p.lat]);if(ring.length&&(ring[0][0]!==ring.at(-1)[0]||ring[0][1]!==ring.at(-1)[1]))ring.push(ring[0]);return {type:'Feature',geometry:{type:'Polygon',coordinates:[ring]},properties:{codigo:feature.propertyCode||feature.parcelCode||feature.id,matricula:feature.registry||'',nome:feature.label,fonte:result.source,consultadoEm:payload.queriedAt}}})});references.push({id:`official-${key}`,name:result.source,type,color:CADASTRAL_COLORS[type],visible:true,official:true,geojson})}}const retained=layers.filter(l=>!l.official||(l.id==='official-car'&&payload.car?.status==='unavailable')||(l.id==='official-sigef'&&payload.sigef?.status==='unavailable'));if(retained.length+references.length>6)throw new Error('Remova uma camada importada para mostrar os resultados oficiais.');publish([...retained,...references]);setOfficialStatus(statuses.join(' '))}catch(e){setError(e.name==='TimeoutError'?'A fonte oficial demorou a responder. Tente novamente.':e.message);setOfficialStatus('Consulta não concluída; referências anteriores preservadas.')}finally{setBusy(false)}
 }
 const publish=(next,filter=query)=>{setLayers(next);onChange(next.filter(l=>l.visible).map(l=>({...l,geojson:filterCadastral(l.geojson,filter)})))}
 const upload=async event=>{
  const selected=event.target.files?.[0];event.target.value='';if(!selected)return
  setBusy(true);setError('')
  try{if(selected.size>5*1024*1024)throw new Error('Use um arquivo de até 5 MB.');if(layers.length>=6)throw new Error('Remova uma camada antes de importar outra (máximo 6).');const geojson=normalizeCadastralGeoJSON(JSON.parse(await selected.text()));publish([...layers,{id:crypto.randomUUID(),name:selected.name,type,color:CADASTRAL_COLORS[type],visible:true,geojson}])}catch(e){setError(e instanceof SyntaxError?'Arquivo inválido. Exporte como GeoJSON WGS84.':e.message)}finally{setBusy(false)}
 }
 return <div className="val-cadastral">{!panelOnly&&<button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><Layers size={16}/>Camadas e cadastros</button>}{(panelOnly||open)&&<div className="val-cadastral-panel"><strong>CAR • SIGEF • Matrículas</strong><button type="button" disabled={busy} onClick={consult}><Search size={16}/>Consultar CAR / SIGEF no centro</button><p>A consulta retorna os imóveis que contêm o ponto central do mapa, na UF selecionada.</p>{officialStatus&&<p role="status">{officialStatus}</p>}<p>Sobreponha limites de arquivos GeoJSON. Referências temporárias desta tela; não vinculam imóveis ao produtor.</p><div className="val-cadastral-upload"><label>Tipo<select value={type} disabled={busy} onChange={e=>setType(e.target.value)}>{CADASTRAL_TYPES.map(t=><option key={t}>{t}</option>)}</select></label><input ref={file} type="file" accept=".geojson,.json" hidden onChange={upload}/><button type="button" disabled={busy} onClick={()=>file.current?.click()}><Upload size={16}/>{busy?'Lendo…':'Importar limite'}</button></div><label><Search size={14}/>Filtrar código / matrícula / nome<input value={query} onChange={e=>{setQuery(e.target.value);publish(layers,e.target.value)}} placeholder="Buscar nos atributos do arquivo"/></label>{!layers.length&&<p>Nenhuma camada carregada.</p>}{layers.map(layer=><div className="val-cadastral-item" key={layer.id}><label><input type="checkbox" checked={layer.visible} onChange={()=>publish(layers.map(l=>l.id===layer.id?{...l,visible:!l.visible}:l))}/><span style={{color:layer.color}}>●</span>{layer.type} · {layer.name} ({filterCadastral(layer.geojson,query).features.length})</label><button type="button" aria-label={`Remover camada ${layer.name}`} onClick={()=>publish(layers.filter(l=>l.id!==layer.id))}><Trash2 size={14}/></button></div>)}<p>Importações: arquivo do usuário. Consultas: fonte oficial indicada na camada. CAR e certificação SIGEF não substituem a conferência da matrícula.</p><nav><a href="https://consultapublica.car.gov.br/publico/imoveis/index" target="_blank" rel="noopener noreferrer">Consulta CAR</a><a href="https://sigef.incra.gov.br/" target="_blank" rel="noopener noreferrer">Consulta SIGEF</a></nav>{error&&<p role="alert">{error}</p>}</div>}</div>
}
