import React,{useRef,useState} from 'react'
import {Layers,Upload,Trash2,Search} from 'lucide-react'
import {CADASTRAL_TYPES,CADASTRAL_COLORS,normalizeCadastralGeoJSON,filterCadastral} from '../../lib/cadastral-map'
export default function CadastralLayers({onChange}){
 const [open,setOpen]=useState(false),[layers,setLayers]=useState([]),[type,setType]=useState('CAR'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const file=useRef(null)
 const publish=(next,filter=query)=>{setLayers(next);onChange(next.filter(l=>l.visible).map(l=>({...l,geojson:filterCadastral(l.geojson,filter)})))}
 const upload=async event=>{
  const selected=event.target.files?.[0];event.target.value='';if(!selected)return
  setBusy(true);setError('')
  try{if(selected.size>5*1024*1024)throw new Error('Use um arquivo de até 5 MB.');if(layers.length>=6)throw new Error('Remova uma camada antes de importar outra (máximo 6).');const geojson=normalizeCadastralGeoJSON(JSON.parse(await selected.text()));publish([...layers,{id:crypto.randomUUID(),name:selected.name,type,color:CADASTRAL_COLORS[type],visible:true,geojson}])}catch(e){setError(e instanceof SyntaxError?'Arquivo inválido. Exporte como GeoJSON WGS84.':e.message)}finally{setBusy(false)}
 }
 return <div className="val-cadastral"><button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><Layers size={16}/>Camadas e cadastros</button>{open&&<div className="val-cadastral-panel"><strong>CAR • SIGEF • Matrículas</strong><p>Sobreponha limites de arquivos GeoJSON. Referências temporárias desta tela; não vinculam imóveis ao produtor.</p><div className="val-cadastral-upload"><label>Tipo<select value={type} disabled={busy} onChange={e=>setType(e.target.value)}>{CADASTRAL_TYPES.map(t=><option key={t}>{t}</option>)}</select></label><input ref={file} type="file" accept=".geojson,.json" hidden onChange={upload}/><button type="button" disabled={busy} onClick={()=>file.current?.click()}><Upload size={16}/>{busy?'Lendo…':'Importar limite'}</button></div><label><Search size={14}/>Filtrar código / matrícula / nome<input value={query} onChange={e=>{setQuery(e.target.value);publish(layers,e.target.value)}} placeholder="Buscar nos atributos do arquivo"/></label>{!layers.length&&<p>Nenhuma camada importada. A consulta automática às bases cadastrais não está conectada.</p>}{layers.map(layer=><div className="val-cadastral-item" key={layer.id}><label><input type="checkbox" checked={layer.visible} onChange={()=>publish(layers.map(l=>l.id===layer.id?{...l,visible:!l.visible}:l))}/><span style={{color:layer.color}}>●</span>{layer.type} · {layer.name} ({filterCadastral(layer.geojson,query).features.length})</label><button type="button" aria-label={`Remover camada ${layer.name}`} onClick={()=>publish(layers.filter(l=>l.id!==layer.id))}><Trash2 size={14}/></button></div>)}<p>Fonte: arquivo fornecido pelo usuário. CAR e certificação SIGEF não substituem a conferência da matrícula.</p><nav><a href="https://consultapublica.car.gov.br/publico/imoveis/index" target="_blank" rel="noopener noreferrer">Consulta CAR</a><a href="https://sigef.incra.gov.br/" target="_blank" rel="noopener noreferrer">Consulta SIGEF</a></nav>{error&&<p role="alert">{error}</p>}</div>}</div>
}
