import {recommendationSnapshot} from './policy.js'
// Canonical joins only. No text/name matching and no current opportunity feature read.
export async function collectLearningSources(c,{tenantId,owners,start,end}){
 const cards=(await c.query("SELECT d.*,cl.source,cl.commercial_profile FROM val_decision_cards d JOIN clients cl ON cl.tenant_id=d.tenant_id AND cl.id=d.client_id AND cl.consultant_id=d.owner_id WHERE d.tenant_id=$1 AND d.owner_id=ANY($2::uuid[]) AND d.generated_at BETWEEN $3 AND $4 ORDER BY d.generated_at,d.id LIMIT 5001",[tenantId,owners,start,end])).rows
 const coach=(await c.query("SELECT d.*,cl.source,cl.commercial_profile FROM val_commercial_coach_cards d JOIN clients cl ON cl.tenant_id=d.tenant_id AND cl.id=d.client_id AND cl.consultant_id=d.owner_id WHERE d.tenant_id=$1 AND d.owner_id=ANY($2::uuid[]) AND d.created_at BETWEEN $3 AND $4 ORDER BY d.created_at,d.id LIMIT 5001",[tenantId,owners,start,end])).rows
 if(cards.length>5000||coach.length>5000)throw Object.assign(new Error('dataset_period_too_large'),{statusCode:422})
 const decisionFeedback=(await c.query('SELECT * FROM val_decision_feedback WHERE tenant_id=$1 AND card_id=ANY($2::uuid[]) AND created_at<=$3',[tenantId,cards.map(d=>d.id),end])).rows
 const coachFeedback=(await c.query('SELECT * FROM val_commercial_coach_feedback WHERE tenant_id=$1 AND card_id=ANY($2::uuid[]) AND created_at<=$3',[tenantId,coach.map(d=>d.id),end])).rows
 const outcomes=(await c.query("SELECT o.*,i.id AS impact_id,i.created_at AS impact_created_at FROM val_outcomes o LEFT JOIN val_observed_impacts i ON i.tenant_id=o.tenant_id AND i.outcome_id=o.id WHERE o.tenant_id=$1 AND o.result->>'decision_card_id'=ANY($2::text[]) AND o.measured_at<=$3",[tenantId,cards.map(d=>d.id),end])).rows
 const decisionMap=new Map(cards.map(d=>[d.id,[]])),coachMap=new Map(coach.map(d=>[d.id,[]]))
 const mapping={USEFUL:'accepted',NOT_USEFUL:'rejected',ACTION_ADAPTED:'edited',ACTION_SELECTED:'scheduled',ACTION_EXECUTED:'executed',ACTION_DISMISSED:'rejected',ADAPTED:'edited',EXECUTED:'executed',DISMISSED:'rejected'}
 for(const [rows,map] of [[decisionFeedback,decisionMap],[coachFeedback,coachMap]])for(const f of rows)map.get(f.card_id)?.push({id:f.id,recommendation_id:f.card_id,tenant_id:f.tenant_id,owner_id:f.owner_id,created_at:f.created_at,kind:'FEEDBACK',value:mapping[f.feedback],source:map===decisionMap?'decision_feedback':'coach_feedback'})
 for(const o of outcomes){const id=o.result.decision_card_id,common={recommendation_id:id,tenant_id:o.tenant_id,owner_id:o.recorded_by,opportunity_id:o.result.opportunity_id||null};decisionMap.get(id)?.push({...common,id:o.id,created_at:o.measured_at,kind:'OUTCOME',value:o.outcome_type==='WON'?'won':o.outcome_type==='LOST'?'lost':o.outcome_type,commercial_proof:o.evidence_refs?.some(r=>r.confirmed===true&&['ORDER','INVOICE','COMMERCIAL_EVENT','CONFIRMED_RECORD'].includes(r.type)&&r.id),source:'outcome_engine'});if(o.impact_id&&Date.parse(o.impact_created_at)<=Date.parse(end))decisionMap.get(id)?.push({...common,id:o.impact_id,created_at:o.impact_created_at,kind:'IMPACT',value:'impact',source:'impact_engine'})}
 return [...cards.map(d=>{
  const timestamp=new Date(d.generated_at).toISOString(),features=Object.fromEntries(Object.entries(d.card.score_breakdown?.dimensions||{}).map(([key,f])=>[key,f.points||0]))
  return {id:d.id,tenant_id:d.tenant_id,owner_id:d.owner_id,account_id:d.client_id,created_at:timestamp,source:d.source||'decision_engine',version:d.card.version||'val.decision-card.v1',displayed:decisionMap.get(d.id).some(l=>l.kind==='FEEDBACK'),synthetic:d.commercial_profile?.synthetic||d.commercial_profile?.isDemo,technical_unreviewed:d.card.status==='REVIEW_REQUIRED',labels:decisionMap.get(d.id),snapshot:recommendationSnapshot({timestamp,engine_version:d.card.version,policy_version:d.policy_version,model_version:'deterministic',features,evidence_refs:(d.card.evidence||[]).map(e=>({id:e.id,known_at:timestamp})),selected_candidate:d.card.opportunity_id,alternatives:d.card.opportunity_id?[{id:d.card.opportunity_id,known_at:timestamp,features,current_score:d.card.priority_score}]:[]})}
 }),...coach.map(d=>{const timestamp=new Date(d.created_at).toISOString();return {id:d.id,tenant_id:d.tenant_id,owner_id:d.owner_id,account_id:d.client_id,created_at:timestamp,source:d.source||'commercial_coach',version:d.card.version||'val.commercial-coach.v1',displayed:coachMap.get(d.id).length>0,synthetic:d.commercial_profile?.synthetic||d.commercial_profile?.isDemo,labels:coachMap.get(d.id),snapshot:recommendationSnapshot({timestamp,engine_version:d.card.version||'val.commercial-coach.v1',policy_version:'val.coach_signals_policy.v1',model_version:'deterministic',features:{confidence:d.card.confidence,evidence_count:d.card.evidence_refs?.length||0},evidence_refs:d.card.evidence_refs||[],selected_candidate:d.card.context?.opportunity||null}),provenance:[{source:'commercial_coach',signal:d.card.signal,canonical_identity:d.id,version:d.card.version,observed_at:timestamp,ingested_at:timestamp}]}})]
}
